<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_BRANCH​​')); 
?>
<?php  $frm = $this->frm_branch;?>
<form id="frm_branch" action="<?php echo $this->url(array('module'=>'global','controller'=>'branch','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
               
                dijit.byId("save_close").attr("disabled",true);
				dijit.byId("save_new").attr("disabled",true);
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="10" style="margin: 0 auto; width:100%">
		<tr>
			<td>
				<fieldset style="background:#fff;   border: solid 1px #008;">
					<legend align="center"><strong><?php echo $tr->translate("BRANCH");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%" cellspacing="10">
									<tr>
										<td><?php echo $tr->translate("CODE")?></td>
										<td><?php echo $frm->getElement("branch_code");?></td>
										<td><?php echo $tr->translate("BRANCH_NAME")?></td>
										<td><?php echo $frm->getElement("branch_nameen");?></td>
										<td><?php echo $tr->translate("PREFIX_CODE");?></td>
									    <td><?php echo $frm->getElement("prefix_code");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("MAIN_BRANCH")?></td>
										<td><?php echo $frm->getElement("main_branch_id");?></td>
										<td><?php echo $tr->translate("ADDRESS")?></td>
										<td><?php echo $frm->getElement("br_address");?></td>
										<td><?php echo $tr->translate("PHONE")?></td>
										<td><?php echo $frm->getElement("branch_tel");?></td>
									</tr>
									<tr>		
										<td><?php echo $tr->translate("BRANCH_FAX")?></td>
										<td><?php echo $frm->getElement("fax");?></td>	
										<td><?php echo $tr->translate("NOTE")?></td>
										<td><?php echo $frm->getElement("branch_note");?></td>
										<td><?php echo $tr->translate("STATUS")?></td>
										<td><?php echo $frm->getElement("branch_status");?></td>
									</tr>
									<tr>
										<td colspan="6" align="center">
											<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" iconClass="dijitIconClear" />
											<input type="button" onClick="submitDataClose()" value="save_close" name="save_close" id="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
											<input type="submit" value="save_new" name="save_new"  id="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconSave" />
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
	</table>	
</form>

<script>

function submitDataClose(){
	if(dijit.byId('frm_branch').validate()) {
		dijit.byId('save_close').set('disabled',true);
		dijit.byId('save_new').set('disabled',true);
		var url_submit = '<?php echo $this->url(array('module'=>'global','controller'=>'branch','action'=>'add')); ?>';
		dojo.xhrPost({
		    url: url_submit,	
			form: dojo.byId("frm_branch"),		    
			load: function(data) {
				alert('<?php echo $tr->translate('INSERT_SUCCESS');?> !');
				window.location.href ="<?php echo $this->baseUrl();?>/global/branch";
			},
			error: function(e) {
			}
		});
	}
}
</script>