<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('UPDATE_BRANCH​​_INFO')); 
?>
<?php  $frm = $this->frm_branch;?>
<form action="<?php echo $this->url(array('module'=>'global','controller'=>'branch','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<table cellspacing="10" style="margin: 0 auto; width:100%">
		<tr>
			<td>
				<fieldset>
					<legend align="center"><strong><?php echo $tr->translate("UPDATE_BRANCH​​_INFO");?></strong></legend>
					<table cellspacing="20" width="100%" >
						<tr>
							<td align="center" valign="top">
								<table width="100%" cellspacing="10">
									<tr>
										<td><?php echo $tr->translate("CODE")?></td>
										<td><?php echo $frm->getElement("branch_code");?></td>
										<td><?php echo $tr->translate("BRANCH_NAME")?></td>
										<td><?php echo $frm->getElement("branch_nameen");?></td>
										<td><?php echo $tr->translate("PREFIX_CODE");?></td>
									    <td><?php echo $frm->getElement("prefix_code");?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("MAIN_BRANCH")?></td>
										<td><?php echo $frm->getElement("main_branch_id");?></td>
										<td><?php echo $tr->translate("ADDRESS")?></td>
										<td><?php echo $frm->getElement("br_address");?></td>
										<td><?php echo $tr->translate("PHONE")?></td>
										<td><?php echo $frm->getElement("branch_tel");?></td>
									</tr>
									<tr>		
										<td><?php echo $tr->translate("BRANCH_FAX")?></td>
										<td><?php echo $frm->getElement("fax");?></td>	
										<td><?php echo $tr->translate("NOTE")?></td>
										<td><?php echo $frm->getElement("branch_note");?></td>
										<td><?php echo $tr->translate("STATUS")?></td>
										<td><?php echo $frm->getElement("branch_status");?></td>
									</tr>
									<tr>
										<td colspan="6" align="center">
										  <input type="reset" label="<?php echo $tr->translate('CLEAR');?>" id="" dojoType="dijit.form.Button"
				                              iconClass="dijitIconClear" />
										  <input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button" 
									          iconClass="dijitEditorIcon dijitEditorIconSave"/>
										</td>
									</tr>					
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		
	</table>	
</form>