<?php 
$dbselect = new Application_Model_DbTable_DbGlobalSelect();
$facebook = $dbselect->getWebsiteSetting("facebook");
$twitter = $dbselect->getWebsiteSetting("twitter");
$instagram = $dbselect->getWebsiteSetting("instagram");
$youtube = $dbselect->getWebsiteSetting("youtube");
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>ពាក្យស្នើសុំ អាហារូបករណ៍ - វិទ្យាស្ថានបច្ចេកទេស ឧស្សាហកម្ម</title>
	<link rel="វិទ្យាស្ថានបច្ចេកទេស ឧស្សាហកម្ម icon" href="<?php echo $this->baseUrl();?>/images/icon.ico" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()."/templates/front/"?>assets/css/imports.css" media="screen">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()."/templates/front/"?>assets/css/bootstrap.min.css" media="screen">
	<link rel="stylesheet" href="<?php echo $this->baseUrl()."/templates/front/"?>assets/chosen/chosen.css">
	
	<link rel="stylesheet" href="<?php echo $this->baseUrl()."/templates/front/"?>assets/kendo/kendo.common-material.min.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl()."/templates/front/"?>assets/kendo/kendo.material.min.css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl()."/templates/front/"?>assets/kendo/kendo.material.mobile.min.css" />
    
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>

<body class="contact">

	<div id="header" class="header-nav-top">

		<!-- main navigation -->
		<div class="header-inner menu-container">
			<div class="navbar-wrapper">
				<nav class="navbar navbar-default mheader" id="nav-main">
					<div class="container-fluid">

						<div class="navbar-header">
								<!---
								<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
								-->
								<a href="<?php echo $this->baseUrl();?>" class=""><img src="<?php echo $this->baseUrl()."/images/headerlogo.jpg"?>" alt="វិទ្យាស្ថានបច្ចេកទេស ឧស្សាហកម្ម"></a>
							</div>

							<div class="collapse navbar-collapse" id="navbar-main">
								
							</div>
					</div>
				</nav>  <!-- end default nav -->
			</div>  <!-- end navbar-wrapper -->
		</div>  <!-- end header-inner -->
	</div> <!-- end header -->


	<!-- Main Content
	================================================== -->
	<div class="main-content container">
		<div class="row">
			<div class="page-title">
				<header class="page-header">
					<h1 class="page-title"><img src="<?php echo $this->baseUrl()."/images/edit.png";?>" />ពាក្យស្នើសុំ អាហារូបករណ៍</h1>
				</header>
			</div>
			<div class="col-md-12 text-center">
				<span id="confirmMessage" class="confirmMessage"></span>
			</div>
			<form onsubmit="return validateForm(this);" class="contact-form" action="#" method="post" enctype="multipart/form-data">
				<div class="main-section col-md-6">
					<div class="entry-content">
						<h3 class="formtitle-blog">
							ប្រវត្តិរូបសង្ខេប
						</h3>
						
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">នាមត្រកូល-នាមខ្លួន <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input type="text" required="required" class="form-control" name="fullName" id="fullName" placeholder="នាមត្រកូល-នាមខ្លួន">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">ជាអក្សរឡាតាំង <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input type="text" class="form-control" name="latinName" id="latinName" placeholder="ជាអក្សរឡាតាំង">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">ភេទ <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<select data-placeholder="ភេទ" class="chosen-select" name="gender" id="gender">
										<option value="m">ប្រុស</option>
										<option value="f">ស្រី</option>
									  </select>
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">ថ្ងៃ-ខែ-ឆ្នាំកំណើត <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input id="calendar" style="width: 100%">
									<input id="dob" name="dob" type="hidden" value="<?php echo date("Y-m-d")?>" style="width: 100%">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">ទីកន្លែងកំណើត</label>
								</div>
								<div class="col-md-8">
									<select data-placeholder="ខេត្ត/ក្រុង" class="chosen-select" name="pobProvince" id="pobProvince">
										<option value="">ជ្រើសរើសខេត្ត/ក្រុង</option>
										<?php if (!empty($this->allProvince)) foreach ($this->allProvince as $rs){?>
										<option value="<?php echo $rs['province_id'];?>" <?php if ($rs['province_id']==1){ echo 'selected="selected"';}?>><?php echo $rs['province_kh_name'];?></option>
										<?php }?>
									</select>
								</div>
								
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
								</div>
								<div class="col-md-8">
									<input type="text" class="form-control" name="pobDistrict" id="pobDistrict"  placeholder="ស្រុក/ខណ្ឌ*">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
								</div>
								<div class="col-md-8">
									<input type="text" class="form-control" name="pobCommune" id="pobCommune"  placeholder="ឃុំ/សង្កាត់*">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
								</div>
								<div class="col-md-8">
									<input type="text" class="form-control" name="pobVillage" id="pobVillage"  placeholder="ភូមិ">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">សញ្ជាតិ <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input type="text" class="form-control" name="nationality" id="nationality" placeholder="សញ្ជាតិ">
								</div>
								<div class="clearboth"></div>
							</div>
							
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">លេខទូរស័ព្ទផ្ទាល់ខ្លួន <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input type="text" required class="form-control" name="phone" id="phone" placeholder="លេខទូរស័ព្ទផ្ទាល់ខ្លួន">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">អុីម៉ែល <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input type="email" required class="form-control" name="email" id="email" placeholder="អុីម៉ែល">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">អាសយដ្ឋានបច្ចុប្បន្ន </label>
								</div>
								<div class="col-md-8">
									<input type="text"  class="form-control" name="currentAddress" id="currentAddress" placeholder="អាសយដ្ឋានបច្ចុប្បន្ន">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">ឈ្មោះអាណាព្យាបាល <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input type="text" required class="form-control" name="guardianName" id="guardianName" placeholder="ឈ្មោះអាណាព្យាបាល">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">អាណាព្យាបាលត្រូវជា <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input type="text" required class="form-control" name="guardianIs" id="guardianIs" placeholder="អាណាព្យាបាលត្រូវជា">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">លេខទូរស័ព្ទអាណាព្យាបាល <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input type="text" required class="form-control" name="guardianPhone" id="guardianPhone" placeholder="លេខទូរស័ព្ទអាណាព្យាបាល">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">រូបថត <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<div class="account-image">
										<div class="image-box">
											<img id="profile_wiew" src="<?php echo $this->baseUrl()."/images/"?>no-profile.png" alt=""  />
										</div>
										<div class="button_browse">
										<div id='preview'></div>	
												<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
												<input class="btn_borwse_image" type="file" id="photo" name="photo" />
										</div>
									</div>
								</div>
								<div class="clearboth"></div>
							</div>

					</div>

				</div> <!-- end main-section -->

				<div class="col-md-6 ">
					<div class="entry-content">
						<h3 class="formtitle-blog">
							ស្នើសុំចូលរៀនកម្មវិធីសិក្សាដូចខាងក្រោម
						</h3>
						<div class="form-group">
							<div class="col-md-4">
								<label class="title-form">ដេប៉ាតឺម៉ង<span class="required">*</span></label>
							</div>
							<div class="col-md-8">
								<select data-placeholder="ដេប៉ាតមង់" onchange="getDegree(),getSkill();" class="chosen-select" name="faculty" id="faculty">
									<option value="">ជ្រើសរើសដេប៉ាតមង់</option>
									<?php if (!empty($this->allFaculty)) foreach ($this->allFaculty as $rs){?>
									<option value="<?php echo $rs['id'];?>"><?php echo $rs['title'];?></option>
									<?php }?>
								</select>
							</div>
							<div class="clearboth"></div>
						</div>
						<div class="form-group">
							<div class="col-md-4">
								<label class="title-form">កម្រិតសិក្សា <span class="required">*</span></label>
							</div>
							<div class="col-md-8">
								<select data-placeholder="កម្រិតសិក្សា" onChange="getSkill();" class="chosen-select" name="degree" id="degree">
								</select>
								
							</div>
							<div class="clearboth"></div>
						</div>
						
						<div class="form-group">
							<div class="col-md-4">
								<label class="title-form">ជំនាញ/វីជ្ជាជីវៈ <span class="required">*</span></label>
							</div>
							<div class="col-md-8">
								<select data-placeholder="ជំនាញ" class="chosen-select" name="skill" id="skill">
									
								</select>
							</div>
							<div class="clearboth"></div>
						</div>
						<div class="form-group">
							<div class="col-md-12 tex-center">
								<span id="documentMessage"></span>
							</div>
							<div class="clearboth"></div>
						</div>
						<div class="form-group">
							<div class="col-md-4">
								<label class="title-form">សញ្ញាបត្រ/ឯកសារពាក់ព័ន្ធ <span class="required">*</span></label>
							</div>
							<div class="col-md-8" id="fileList">
									
							</div>
							<div class="clearboth"></div>
						</div>
						<div class="form-group">
							<div class="col-md-4">
							</div>
							<div class="col-md-8">
								<button class="btn btn-default addfile" onclick="addRow();" type="button">បន្ថែមឯកសារ</button>
								<input type="hidden" name="identity" id="identity"  value="" >
							</div>
						</div>	
							
					</div>
					<div class="entry-content">
						<h3 class="formtitle-blog">
							ប្រវត្តិការសិក្សា
						</h3>
						<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">កម្រិតវប្បធម៌ </label>
								</div>
								<div class="col-md-8">
									<input type="text"  class="form-control" name="education" id="education" placeholder="កម្រិតវប្បធម៌">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">លេខកូដសញ្ញាបត្រ </label>
								</div>
								<div class="col-md-8">
									<input type="text"  class="form-control" name="certificateNo" id="certificateNo" placeholder="ឧទា : ៣៦៩/១៧">
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">មកពីវិទ្យាល័យ <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<input type="text" required="required" class="form-control" name="fromhightschool" id="fromhightschool" placeholder="មកពីវិទ្យាល័យ" >
								</div>
								<div class="clearboth"></div>
							</div>
							<div class="form-group">
								<div class="col-md-4">
									<label class="title-form">ខេត្ត/ក្រុង <span class="required">*</span></label>
								</div>
								<div class="col-md-8">
									<select data-placeholder="ខេត្ត/ក្រុង" class="chosen-select" name="province" id="province">
										<option value="">ជ្រើសរើសខេត្ត/ក្រុង</option>
										<?php if (!empty($this->allProvince)) foreach ($this->allProvince as $rs){?>
										<option value="<?php echo $rs['province_id'];?>" <?php if ($rs['province_id']==1){ echo 'selected="selected"';}?>><?php echo $rs['province_kh_name'];?></option>
										<?php }?>
									</select>
								</div>
								<div class="clearboth"></div>
							</div>
					</div>
				</div> <!-- end column -->
				<div class="col-md-12 text-center button-sumbit ">
					<button type="submit" class="btn btn-default">ដាក់ស្នើ</button>
				</div>
				<div class="noteblog col-md-12">
					<h3>បញ្ជាក់៖</h3>
					<div class="noteDescriptoin">
						<ul>
							<li>សញ្ញា ( <span class="required">*</span> ) បញ្ជាក់ថាចាំបាច់ត្រូវតែបញ្ចូលទិន្នន័យជាចាំបាច់។</li>
							<li>ត្រូវភ្ជាប់សញ្ញាបត្រ/ឯកសារពាក់ព័ន្ធ (ឧទា. សញ្ញាប័ត្រមធ្យមសិក្សាទុតិយភូម...) ដើម្បីបំពេញលក្ខខណ្ឌរបស់វិទ្យាស្ថាន។</li>
							<li>អ្នកនឹងទទួលបានសារអេឡិចត្រូនិច (Email)មួយដែលបញ្ចាក់ថាការស្នើររបស់អ្នកបានបញ្ជូនមកកាន់ វិទ្យាស្ថានបច្ចេកទេសឧស្សាហកម្ម។</li>
							<li>បន្ទាប់ពីអ្នកធ្វើការស្នើខាង វិទ្យាស្ថានបច្ចេកទេសឧស្សាហកម្មនិងផ្ដល់ដំណឹងទៅអ្នកតាមរយៈសារអេឡិចត្រូនិច (Email)។</li>
						</ul>
					</div>
				</div>
			</form> <!-- contact-form -->
		</div> <!-- end container -->
	</div> <!-- end main-content -->


	<!-- Footer
	================================================== -->
	<footer id="footer" class="wrapper with-overlap">

		<div class="container">
			<div class="row">

				<div class="col-md-12">

					<ul class="footer-social icon-blocks">
						<li><a href="<?php echo $facebook['value'];?>" target="_blank"><i class="fa fa-facebook"></i></a></li>
						<li><a href="<?php echo $twitter['value'];?>" target="_blank"><i class="fa fa-twitter"></i></a></li>
						<li><a href="<?php echo $instagram['value'];?>" target="_blank"><i class="fa fa-instagram"></i></a></li>
						<li><a href="<?php echo $youtube['value'];?>" target="_blank"><i class="fa fa-youtube"></i></a></li>
					</ul>

					<div class="copyright">
						<p>&copy; វិទ្យាស្ថានបច្ចេកទេសឧស្សាហកម្ម 2018.<br>ភ្នំពេញ, ព្រះរាជាណាចក្រកម្ពុជា</p>
					</div>


				</div>

			</div>

		</div>
	</footer>
	<?php 
	$session_messagesent=new Zend_Session_Namespace('messagesent');
	$message =	$session_messagesent->success;
	$session_messagesent->unsetAll();
	?>
	<div id="messagebox" class="messagebox <?php if ($message==1 || $message==2){ echo "open";}else{ echo "close";}?>">
    	<div class="container">
                <div class="row">
                	<div class="col-md-2 col-sm-2">
					</div><!-- /.col-md-12 -->
					<div class="col-md-8 col-sm-8 text-center message_content" >
						<div class="message_content_des">
							<?php if ($message==1){?>
							ការស្នើសុំ អាហារូបករណ៍របស់អ្នក មកកាន់ <strong>វិទ្យាស្ថានបច្ចេកទេសឧស្សាហកម្ម</strong> បានបញ្ជូនរួចរាល់ហើយ<br />
							សូមអរគុណ
							<?php }else{?>
							HTTP/1.1 500 Could not send mail! Sorry..
							<?php }?>
						</div>
						<a id="closemessage" class="button button-submit" href="javascript:void(0)">បិទ</a>
					</div>
					<div class="col-md-2 col-sm-2">
					</div><!-- /.col-md-12 -->
    			</div>
    	</div>
    </div>
	<div class="overlay">
		<div class="overlay-load">
			<div class="overlay-msg">
		    </div>
		</div>
	</div>
	<script src="<?php echo $this->baseUrl()."/templates/front/"?>assets/js/jquery-1.11.3.min.js"></script>
	<script src="<?php echo $this->baseUrl()."/templates/front/"?>assets/js/bootstrap.min.js"></script>
	<script src="<?php echo $this->baseUrl()."/templates/front/"?>assets/chosen/chosen.jquery.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl()."/templates/front/"?>assets/chosen/init.js" type="text/javascript" charset="utf-8"></script>
	<script src="<?php echo $this->baseUrl()."/templates/front/"?>assets/js/custom.js"></script>
	
	
	

    <script src="<?php echo $this->baseUrl()."/templates/front/"?>assets/kendo/js/kendo.all.min.js"></script>
	<script src="<?php echo $this->baseUrl()."/templates/front/"?>assets/web.js"></script>
    
<script>
var urlDegree='<?php echo $this->url(array('controller'=>'index','action'=>'getdegree')); ?>';
var urlSkill='<?php echo $this->url(array('controller'=>'index','action'=>'getskill')); ?>';
</script>
</body>
</html>