<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?php echo $tr->translate("Ministry of Industry and Handicraft");?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta content="Black & White Cabs" name="description" />
        <meta content="Black & White Cabs" name="author" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <!-- App favicon -->
        <link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/images/icon.ico" type="image/x-icon"/>

        <!-- App css -->
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/css/icons.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/css/metismenu.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/css/style.css" rel="stylesheet" type="text/css" />

        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/modernizr.min.js"></script>

    </head>


    <body>

        <section>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">

                        <div class="wrapper-page">

                            <div class="m-t-40 card-box">
                                <div class="text-center">
                                    <h2 class="text-uppercase m-t-0 m-b-30">
                                        <a href="<?php echo $this->baseUrl();?>" class="text-success">
                                            <span><img src="<?php echo $this->baseUrl()."/images/lang/logo.png";?>" alt="" height="85px"></span>
                                        </a>
                                    </h2>
                                   <div class="message"><?php echo $this->msg;?></div>
                                </div>
                                <div class="account-content">
                                    <form id="frmLogin" class="form-horizontal" action="" method="post">
                                        <div class="form-group m-b-20">
                                            <div class="col-xs-12">
                                                <label for="emailaddress"><?php echo $tr->translate("User Name");?></label>
                                                <input class="form-control" type="text" id="user_name" name="user_name" required="" >
                                            </div>
                                        </div>

                                        <div class="form-group m-b-20">
                                            <div class="col-xs-12">
                                                <label for="password"><?php echo $tr->translate("Password");?></label>
                                                <input type="password" class="form-control" type="txt_password" required="" id="txt_password" name="txt_password" placeholder="<?php echo $tr->translate("Enter your password");?>">
                                            	<?php if (!empty($this->information)) {?>
                                            	<input type="hidden" class="form-control"  id="information" name="information" value="<?php echo $this->information;?>">
                                            	<?php }?>
                                            </div>
                                        </div>
                                        <div class="form-group account-btn text-center m-t-10">
                                            <div class="col-xs-12">
                                                <button class="btn btn-lg btn-primary btn-block" type="submit"><?php echo $tr->translate("Sign In");?></button>
                                            </div>
                                        </div>
                                    </form>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <!-- end card-box-->

                        </div>
                        <!-- end wrapper -->

                    </div>
                </div>
            </div>
        </section>


        <!-- jQuery  -->
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/jquery.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/popper.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/metisMenu.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/waves.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/jquery.slimscroll.js"></script>

        <!-- App js -->
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/jquery.core.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/jquery.app.js"></script>
    </body>
</html>