<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('Add Privacy'));
echo $this->headTitle();
?>
 <!-- START PAGE CONTENT -->
 <script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
 
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-star	"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Add Privacy")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/other/privacy/index";?>"><?php echo $tr->translate("GO_BACK")?></a>
    			</div>
    		</div>
    		
			<div class="col-sm-12">
				<form id="frm" class="form-horizontal form-label-left" action=""  method="post" enctype="multipart/form-data">
	                <div class="form-group">
	                   <label class="control-label col-md-1 col-sm-1 col-xs-1" for="first-name"><?php echo $tr->translate('DESCRIPTION')?>:
	                   </label>
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<textarea class="ckeditor"  rows="1"   id="disciption" name="disciption" required ><?php echo $this->row['description']?></textarea>
	                   		<input type="hidden" id="id" name="id" value="<?php echo $this->row['id']?>" >
	                   </div>
	                </div>
	              <!-- 
	                 <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-2" for="first-name"><?php echo $tr->translate('ORDER_BY')?> :
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-4">
	                    	<input class="form-control"  type="text"  name="order_by" id="order_by" placeholder="<?php echo $tr->translate('ORDER_BY')?>"/>
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-2" for="first-name"><?php echo $tr->translate('STATUS')?> :
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-4">
	                    	<select class="form-control select2" id="status"  name="status"  > 
	                   			<option value="1"  ><?php echo $tr->translate('ACTIVE')?></option>
	                   			<option value="0"  ><?php echo $tr->translate('DEACTIVE')?></option>
							</select>
	                   </div>
	                </div>
	                  -->   
                    <div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-right">
								<input class="btn btn-primary black save" name="save_new"  id="save_new" type="submit" value="<?php echo $tr->translate('SAVE_NEW');?>" label="<?php echo $tr->translate('SAVE_NEW');?>" id="submitButton" /> 
			                </div>
	                    </div>
                    </div>
	               
	              </form>
			</div>
 
<script type="text/javascript">
	$('#frm').submit(function() {
		disciption = $("#disciption").val();
	    if(disciption==null || disciption==-1){
	        alert("<?php echo $tr->translate('Please Input Description!')?>");
	        return false;
	    }
		var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
		if (r == true) {
		    return true;
		} else {
		   return false;
		}
	});
</script>