<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("Supplier")); 
	echo $this->headTitle();
	
?>   
<style>
img.status_icon {
    width: 16px;
}
div.search {
    padding: 0 2px;
    margin: 0;
}
span.select2.select2-container.select2-container--default {
    width: 100% !important;
}
</style> 
 <!-- START PAGE CONTENT -->
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Supplier")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    				<div class="buttun-block">
						<a class="btn btn-primary black save" href="<?php echo $this->baseUrl()."/supplyer/index/add";?>"><?php echo $tr->translate("Add New")?></a>
					</div>
    			</div>
    		</div>
			<div class="col-sm-12">
				<div class="card-box">
					<form name="frmlist_users" action=""  method="post" autocomplete="off">
						<div class="form-group">
                            <div class="col-md-4">
                                <input type="text" class="form-control" name="adv_search" id="adv_search"  placeholder="<?php echo $tr->translate("Search Here");?>" value='<?php echo $this->search['adv_search'];?>'>
								 </div>
                            <div class="col-md-1">
                            </div>
                             <div class="col-md-8 text-right">
                            	 <div class="form-group">
                                   	<div class="col-md-6 search">
                                     	<div class="input-daterange input-group" id="date-range">
                                          	<input type="text" class="form-control" name="start" value="<?php if (!empty($this->search['start'])){ echo date("d-m-Y",strtotime($this->search['start']));}?>" />
                                            <span class="input-group-addon b-0"><?php echo $tr->translate("to");?></span>
                                            <input type="text" class="form-control" name="end" value="<?php if (!empty($this->search['end'])){ echo date("d-m-Y",strtotime($this->search['end']));}?>" />
                                       </div>
                                   	</div>
                                   	<div class="col-md-3 text-left search">
					                 	  <select class="form-control select2" id="status"  name="status"  > 
					                 	  		<option value="-1"><?php echo $tr->translate('Status')?></option>
					                   			<option value="1" <?php if ($this->search['status']==1){ echo 'selected="selected"';}?>><?php echo $tr->translate('Active')?></option>
					                   			<option value="0" <?php if ($this->search['status']==0){ echo 'selected="selected"';}?>><?php echo $tr->translate('Deactive')?></option>
											</select> 
					                   </div>
                                   <div class="col-md-1 search">
                                   	<button class="btn btn-primary " showLabel="true" type="submit"><?php echo $tr->translate("Search");?></button>
                                   	 </div>
                                 </div>
                            </div>
                       </div>
					</form>
					<div class="clearfix"></div>
				</div>
				<?php 
				   echo $this->list;
				?>
			</div>
<!-- END PAGE CONTENT -->
