<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("SUPPLYER")); 
	echo $this->headTitle();
	
?>   
<style>
img.status_icon {
    width: 16px;
}
div.search {
    padding: 0 2px;
    margin: 0;
}
span.select2.select2-container.select2-container--default {
    width: 100% !important;
}
</style> 
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("SUPPLYER")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    				<div class="buttun-block">
						<a class="btn btn-primary black save" href="<?php echo $this->baseUrl()."/supplyer/index/add";?>"><?php echo $tr->translate("Add Supplyer")?></a>
					</div>
    			</div>
    		</div>
			<div class="col-sm-12">
				<div class="card-box">
					<form name="frmlist_users" action=""  method="post" autocomplete="off">
						<div class="form-group">
                            <div class="col-md-4">
                                <input type="text" class="form-control" name="adv_search" id="adv_search"  placeholder="<?php echo $tr->translate("Search by employee id");?>" value='<?php echo $this->search['adv_search'];?>'>
								 </div>
                            <div class="col-md-1">
                            </div>
                             <div class="col-md-8 text-right">
                            	 <div class="form-group">
                                   	<div class="col-md-6 search">
                                     	<div class="input-daterange input-group" id="date-range">
                                          	<input type="text" class="form-control" name="start" value="<?php if (!empty($this->search['start'])){ echo date("m/d/Y",strtotime($this->search['start']));}?>" />
                                            <span class="input-group-addon b-0"><?php echo $tr->translate("to");?></span>
                                            <input type="text" class="form-control" name="end" value="<?php if (!empty($this->search['end'])){ echo date("m/d/Y",strtotime($this->search['end']));}?>" />
                                       </div>
                                   	</div>
                                   	<div class="col-md-3 text-left search">
					                 	  <select class="form-control select2" id="status"  name="status"  > 
					                 	  		<option value="-1"><?php echo $tr->translate('STATUS')?></option>
					                   			<option value="1" <?php if ($this->search['status']==1){ echo 'selected="selected"';}?>><?php echo $tr->translate('ACTIVE')?></option>
					                   			<option value="0" <?php if ($this->search['status']==0){ echo 'selected="selected"';}?>><?php echo $tr->translate('DEACTIVE')?></option>
											</select> 
					                   </div>
                                   <div class="col-md-1 search">
                                   	<button class="btn btn-primary " showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                                   	 </div>
                                 </div>
                            </div>
                       </div>
					</form>
					<div class="clearfix"></div>
				</div>
				<?php 
				   echo $this->list;
				?>
				<?php /*?>
				
				<table id="datatable-buttons" class="table table-striped table-bordered">
					<thead>
    					<tr>
    						<th><?php echo $tr->translate("NUM");?></th>
    						<th><?php echo $tr->translate("Employee ID");?></th>
    						<th><?php echo $tr->translate("First Name Last Name");?></th>
    						<th><?php echo $tr->translate("Gender");?></th>
    						<th><?php echo $tr->translate("Framework");?></th>
    						<th><?php echo $tr->translate("POSITION");?></th>
    						<th><?php echo $tr->translate("Phone Number");?></th>
    						<th><?php echo $tr->translate("STATUS");?></th>
    						<th><?php //echo $tr->translate("STATUS");?></th>
    					</tr>
    				</thead>
    				<tbody>
    					<?php 
    					if (!empty($this->allemployee)) 
    						foreach ($this->allemployee as $key => $employee){
    							$images = $this->baseUrl()."/images/icon/active.png";
    							if ($employee['status']!=1){
    								$images = $this->baseUrl()."/images/icon/blocked.png";
    							}
    						?>
    					<tr>
    						<td><?php echo $key+1;?></td>
    						<td><a class="edit" href="<?php echo $urledit."/id/".$employee['id'];?>"><?php echo $employee['employeeCode'];?></a></td>
    						<td><a class="edit" href="<?php echo $urledit."/id/".$employee['id'];?>"><?php echo $employee['firstName']." ".$employee['sureName'];?></a></td>
    						<td><?php echo $employee['gender'];?></td>
    						<td><?php echo $employee['framework'];?></td>
    						<td><?php echo $employee['position'];?></td>
    						<td><?php echo $employee['phoneNumber'];?></td>
    						<td class="text-center"><img class="status_icon" src="<?php echo $images;?>" /></td>
    						<td>
	    						<a title="<?php echo $tr->translate("Delete Now"); ?>" data-toggle="modal" data-target="#myModal" class="btn btn-app small" onclick="showDeleteForm(<?php echo $employee['id'];?>)">
			                      <i class="fa fa-trash"></i>
			                    </a>
		                    </td>
    					</tr>
    					<?php }?>
    				</tbody>
				</table>
				
				<?php */?>
				
			</div>
		</div>
	</div>
</div>
<!-- END PAGE CONTENT -->
<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title text-center"><?php echo $tr->translate("Would you want to delete this record");?></h4>
        </div>
        <div class="modal-body text-center">
          	<button type="button" class="btn btn-primary block" onclick="deleteRecord('<?php echo $url_delete;?>')" ><?php echo $tr->translate("Delete Now");?></button>
          	<button type="button" class="btn btn-primary unblock"  data-dismiss="modal"><?php echo $tr->translate("Close");?></button>
        </div>
      </div>
      
    </div>
  </div>
<script>
var timeout ='<?php echo $timeload;?>';
function PrintDiv() {
	loading();
    var contents = document.getElementById("divPrint").innerHTML;
    var frame1 = document.createElement('iframe');
    frame1.name = "frame1";
    frame1.style.position = "absolute";
    frame1.style.top = "-1000000px";
    document.body.appendChild(frame1);
    var frameDoc = (frame1.contentWindow) ? frame1.contentWindow : (frame1.contentDocument.document) ? frame1.contentDocument.document : frame1.contentDocument; frameDoc.document.open();
    frameDoc.document.write('<html><head><title>Employee ID</title>');
    frameDoc.document.write('</head><body>');
    frameDoc.document.write(contents);
    frameDoc.document.write('</body></html>');
    frameDoc.document.close();
    setTimeout(function () {
        window.frames["frame1"].focus();
        window.frames["frame1"].print();
        document.body.removeChild(frame1);
        closeloading();
    }, timeout);
   return false;
}
var recordid ='';
function deleteRecord(url){
	loading();
	 id = recordid;
	 window.location.href = url+'/id/'+id;
}
function showDeleteForm(id){
	if(id==''){
		recordid='';
	}else{
		recordid = id;
	}
}
</script>