<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('Edit Partner'));
	echo $this->headTitle();

	$photo = $this->baseUrl()."/images/profile.jpg";
	$partner = $this->partner;
	$file="";
	if (!empty($partner['photo'])){
		$photo = $this->baseUrl()."/images/all/partner/".$partner['photo'];
		$file= $partner['photo'];
	}
?>
<style>
.form-group {
    margin-bottom: 5px;
}
.form-horizontal .control-label {
    text-align: left;
}
.thumb-xl {
    height: 180px;
    width: 150px;
}
div.browe_photo .input-group {
    display: block;
}
label#error {
    color: #F44336;
}
.card-employee {
    border: solid 1px #cecccc;
    border-radius: 5px;
    width: 14cm;
    padding: 10px;
        color: #0670c3;
}
</style>
 <!-- START PAGE CONTENT -->
    		<form id="frm" class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" autocomplete="off">
	    		<div class="col-sm-12 border-botom">
	    			<div class="col-sm-8">
	    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Edit Partner");?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    				<input id="backbutton" class="btn btn-primary block" type="button" onclick="window.location = '<?php echo $this->url(array('module'=>'other','controller'=>"partner",'action'=>'index'),null,true); ?>';" value="<?php echo $tr->translate('GO_BACK');?>" />
	    			</div>
	    		</div>
    		
				<div class="col-sm-8">
					<div class="form-group">
						<label id="error" class="col-md-12 col-sm-12 col-xs-12 text-center" ></label>
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">
	                   		<?php echo $tr->translate('Partner Name')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                    	<input class="form-control" type="text"  name="partnerName" id="partnerName" value="<?php echo $partner['partnerName']?>" placeholder="<?php echo $tr->translate('Partner Name')?>"/>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Ordering')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control" name="ordering" id="ordering" value="<?php echo $partner['ordering']?>" placeholder="<?php echo $tr->translate('Ordering');?>" />
	                   </div>
	                </div>

	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Website')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control" name="website" id="website" value="<?php echo $partner['website']?>" placeholder="<?php echo $tr->translate('Website');?>" />
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Note')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control" name="note" id="note" value="<?php echo $partner['note']?>" placeholder="<?php echo $tr->translate('Note');?>" />
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Status')?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-7">
						  <select class="form-control select2me" name="status" id="status" placeholder="<?php echo $tr->translate('Status')?>" >
								<option value="1" <?php if($partner['status']==1){echo "selected='selected'";}?>><?php echo $tr->translate('Active')?></option>
								<option value="0" <?php if($partner['status']==0){echo "selected='selected'";}?>><?php echo $tr->translate('Deactive')?></option>
	                      </select>
					   </div>
	                </div>
	                
				</div>
				<div class="col-sm-4">
					<div class="form-group">
						<div class="col-md-12 col-sm-12 col-xs-12 text-center">
	                    	<div class="thumb-xl member-thumb m-b-10 center-block">
	                            <img id="profile-img-tag" src="<?php echo $photo;?>" class=" img-thumbnail" alt="profile-image" >
		                        </div>
	                        </div>
	                 </div>
	                 <div class="form-group">
	                       <div class="col-md-12 col-sm-12 col-xs-12 m-t-10 text-center browe_photo">
	                        <input type="file" id="profile-img" class="filestyle" data-input="false" name="photo" data-buttontext="<?php echo $tr->translate('Photo')?>">
	                  	  </div>
					 </div>
					 
					 
					 <div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-center">
	                    	 	<input type="hidden" name="oldLogo" id="oldLogo" class="form-control" value="<?php echo $partner['photo']?>" />
			                </div>
	                    </div>
                    </div>
				</div>
				
				<div class="col-sm-12">
                	<div class="form-group">
	                    &nbsp;
                    </div>
				</div>
				
				<div class="col-sm-12">
                	<div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-center">
								<input id="btnsubmit" class="btn btn-primary black save" type="submit" value="<?php echo $tr->translate('Edit');?>" id="submitButton" /> 
			                </div>
	                    </div>
                    </div>
				</div>
				
			</form>
<script type="text/javascript">
	
	$('#frm').submit(function() {
		partnerName=$("#partnerName").val();
		if(partnerName==''){
			$('#partnerName').focus();
			return false;	
		}
		ordering=$("#ordering").val();
		if(ordering==""){
			$('#ordering').focus();
			return false;	
		}
		$("#btnsubmit").attr("disabled", true);
		return true;
	});

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });

</script>