<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("Partner Service")); 
	echo $this->headTitle();
?>   
<style>
img.status_icon {
    width: 16px;
}
div.search {
    padding: 0 2px;
    margin: 0;
}
span.select2.select2-container.select2-container--default {
    width: 100% !important;
}
</style> 
 <!-- START PAGE CONTENT -->
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Partner Service")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    				<div class="buttun-block">
						<a class="btn btn-primary black save" href="<?php echo $this->baseUrl()."/other/partner/add";?>"><?php echo $tr->translate("Add New")?></a>
					</div>
    			</div>
    		</div>
			<div class="col-sm-12">
				<div class="card-box">
					<form name="frmlist_users" action=""  method="post" autocomplete="off">
						<div class="form-group">
                            <div class="col-md-3">
                                <input type="text" class="form-control" name="adv_search" id="adv_search"  placeholder="<?php echo $tr->translate("Search Here");?>" value='<?php echo $this->search['adv_search'];?>'>
							</div>
							<div class="col-md-3 text-left search">
		                 	  	<select class="form-control select2" id="status"  name="status"  > 
		                 	  		<option value="-1"><?php echo $tr->translate('Status')?></option>
		                   			<option value="1" <?php if ($this->search['status']==1){ echo 'selected="selected"';}?>><?php echo $tr->translate('Active')?></option>
		                   			<option value="0" <?php if ($this->search['status']==0){ echo 'selected="selected"';}?>><?php echo $tr->translate('Deactive')?></option>
								</select> 
		                    </div>
							<div class="col-md-2 search">
                            	<button class="btn btn-primary " showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                            </div>
                        </div>
					</form>
					<div class="clearfix"></div>
				</div>
				<?php 
				   echo $this->list;
				?>
			</div>
