<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("Add Vehicle Type")); 
	echo $this->headTitle();
	$urledit = $this->baseUrl()."/vehicle/vehicletype/edit";
?>   
<style>
img.status_icon {
    width: 16px;
}
</style> 
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-star"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Add Vehicle Type")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    				<div class="buttun-block">
						<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/vehicle/vehicletype/add";?>"><?php echo $tr->translate("Add Vehicle Type")?></a>
					</div>
    			</div>
    		</div>
    		
			<div class="col-sm-12">
			<form name="frmlist_users" action=""  method="post">
						<div class="form-group">
                            <div class="col-md-3">
                                <input type="text" class="form-control" name="adv_search" id="adv_search"  placeholder="<?php echo $tr->translate("SEARCH_INFO");?>" value='<?php echo $this->search['adv_search'];?>'>
							</div>
                            <div class="col-md-3">
                                <select class="form-control select2" id="status"  name="status"  > 
		                 	  		<option value="-1"><?php echo $tr->translate('STATUS')?></option>
		                   			<option value="1" <?php if ($this->search['status']==1){ echo 'selected="selected"';}?>><?php echo $tr->translate('ACTIVE')?></option>
		                   			<option value="0" <?php if ($this->search['status']==0){ echo 'selected="selected"';}?>><?php echo $tr->translate('DEACTIVE')?></option>
								</select> 
							</div>
							<div class="col-md-3">
                                <button class="btn btn-primary " showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
							</div>
                       </div>
					</form>
					<div class="clearfix"></div>
				<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
					<thead>
    					<tr>
    						<th><?php echo $tr->translate("NUM");?></th>
    						<th><?php echo $tr->translate("Service Type");?></th>
    						<th><?php echo $tr->translate("Vehicle Type Name");?></th>
    						<th><?php echo $tr->translate("Amount Sit");?></th>
    						<th><?php echo $tr->translate("ចំនួនវាលីធំ");?></th>
    						<th><?php echo $tr->translate("ចំនួនវាលីតូច");?></th>
    						<th><?php echo $tr->translate("Description");?></th>
    						<th><?php echo $tr->translate("Image");?></th>
    						<th><?php echo $tr->translate("Create Date");?></th>
    						<th><?php echo $tr->translate("Modify Date");?></th>
    						<th><?php echo $tr->translate("Status");?></th>
    					</tr>
    				</thead>
    				<tbody>
    					<?php $images="";  
    					if (!empty($this->vehicle)) 
    						foreach ($this->vehicle as $key => $rs){
    							if ($rs['status']==1){
    							    $images = $this->baseUrl()."/images/icon/active.png";
    							}else{
    							    $images = $this->baseUrl()."/images/icon/blocked.png";
    							}
    							
    							if($rs['images']!=''){
    							    $img=$this->baseUrl()."/images/all/".$rs['images'];
    							}else {
    							    $img=$this->baseUrl()."/images/no-img.jpg";
    							}
    						?>
    					<tr>
    						<td><?php echo $key+1;?></td>
    						<td><a class="edit" href="<?php echo $urledit."/id/".$rs['id'];?>"><?php echo $rs['service_name'];?></a></td>
    						<td><a class="edit" href="<?php echo $urledit."/id/".$rs['id'];?>"><?php echo $rs['title'];?></a></td>
    						<td><a class="edit" ><?php echo $rs['amountSeat'];?></a></td>
    						<td><a class="edit" ><?php echo $rs['amountCase'];?></a></td>
    						<td><a class="edit" ><?php echo $rs['amountSmallCase'];?></a></td>
    						<td><a class="edit" ><?php echo $rs['description'];?></a></td>
    						<td><?php  echo "<img src = ".$img." height='50px'  alt = ''/>";?></td>
    						<td><?php if (!empty($rs['createDate'])){ echo date("H:i:s d M Y",strtotime($rs['createDate']));}?></td>
    						<td><?php if (!empty($rs['modifyDate'])){ echo date("H:i:s d M Y",strtotime($rs['modifyDate']));}?></td>
    						<td class="text-center"><img class="status_icon" src="<?php echo $images;?>" /></td>
    					</tr>
    					<?php }?>
    				</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<!-- END PAGE CONTENT -->