
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
?>
<title><?php echo $tr->translate('Change Password')?></title>

<!-- START PAGE CONTENT -->
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-user"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Change Password")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    		
			<div class="col-sm-8">
				<form  class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<?php if (!empty($this->msg)){?> <p style="clear: both;  color: #f00;"><?php echo $this->msg; ?></p><?php }?>
					<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('OLD_PASSWORD')?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                     <input type="password" class="form-control"  required="true" name="current_password" id="current_password" placeholder="<?php echo $tr->translate('OLD_PASSWORD')?>" regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
												missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពាក្យ​​សំងាត់!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('PASSWORD')?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                     <input type="password" class="form-control"  required="true" name="password" id="password" placeholder="<?php echo $tr->translate('PASSWORD')?>" regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
												missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពាក្យ​​សំងាត់!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="text-right">
		                <input class="btn btn-primary black" type="button" value="<?php echo $tr->translate('GO_BACK');?>" label="<?php echo $tr->translate('GO_BACK');?>" id="back" 	 onclick="window.location = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>"user",'action'=>'index'),null,true); ?>';" />
						<input class="btn btn-primary black" type="submit" value="<?php echo $tr->translate('SAVE');?>" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" /> 
	                </div>
	                <input type="hidden" id="agent" name="agent" value="0" />
	              </form>
			</div>
