<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('EDIT_USER'));
echo $this->headTitle();
?>
<!-- START PAGE CONTENT -->
 
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-user"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("EDIT_USER")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    				<div class="buttun-block">
    					<?php if ($this->user_edit['active']==1){?>
						<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/rsvacl/user/update?status=0&id=".$this->user_edit['id'];?>"><?php echo $tr->translate("DEACTIVE")?></a>
						<?php }else if ($this->user_edit['active']==0){?>
						<a class="btn btn-primary unblock" href="<?php echo $this->baseUrl()."/rsvacl/user/update?status=1&id=".$this->user_edit['id']?>"><?php echo $tr->translate("ACTIVE")?></a>
						<?php }?>
					</div>
    			</div>
    		</div>
    		
			<div class="col-sm-8">
				<form  class="form-horizontal form-label-left" action="<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					
					<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" value="<?php echo $this->user_edit['first_name'];?>" for="first-name"><?php echo $tr->translate('FULL_NAME')?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	<input class="form-control"  type="text" required="true" name="first_name" id="first_name" value="<?php echo $this->user_edit['first_name'];?>" placeholder="<?php echo $tr->translate('FULL_NAME')?>" missingMessage="អ្នក​ភ្លេច​បំពេញ​ នាមខ្លួន!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('EMAIL')?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                      <input class="form-control" type="text" required="true" name="email" id="email" value="<?php echo $this->user_edit['email'];?>" placeholder="<?php echo $tr->translate('EMAIL')?>" 
												 missingMessage="អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ប្រើ​ប្រាស់!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('PASSWORD')?><span class="required">* <input type="checkbox" id="check_change" name="check_change" onChange="Checkchange();" /></span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                     <input type="password" class="form-control"  required="true" name="password" id="password" placeholder="<?php echo $tr->translate('PASSWORD')?>" regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
												missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពាក្យ​​សំងាត់!" class='fullside'/>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('USER_TYPE')?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                   <select class="form-control"  name="user_type" class='fullside' required="true" id="user_type" 
							 missingMessage="អ្នក​ភ្លេច​បំពេញ​  តំណែង!" dojoType="dijit.form.FilteringSelect"> 
								<?php foreach ($this->user_typelist as $key => $ust) : ?>
									<option value="<?php echo $key;?>" <?php if($this->user_edit['user_type'] == $key) echo 'selected';?>><?php echo $ust;?></option>
								<?php endforeach;?>																					
							</select> 
	                   </div>
	                </div>
	                <div class="text-right">
		                <input class="btn btn-primary black" type="button" value="<?php echo $tr->translate('GO_BACK');?>" label="<?php echo $tr->translate('GO_BACK');?>" id="back" 	 onclick="window.location = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>"user",'action'=>'index'),null,true); ?>';" />
						<input class="btn btn-primary black" type="submit" value="<?php echo $tr->translate('SAVE');?>" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" /> 
	                </div>
	               <input type="hidden" name="id" value="<?php echo $this->user_edit['id'];?>" />
	              </form>
			</div>

 <div class="title_left">
 	<h3><i class="fa fa-user" aria-hidden="true"></i> <?php echo $tr->translate("USER")?></h3>
 </div>
<script>
$(document).ready(function(){
	try{
		Checkchange();
	}catch(e){
		alert(e);
	}
	$(window).keydown(function(event){
		if(event.keyCode == 13) {
		  event.preventDefault();
		  return false;
		}
	  });
});
function Checkchange(){
	if ($('#check_change').is(':checked')) {
		  $("#password").prop('required',true);
		  $("#password").removeAttr('readonly');

		  $("#con_password").prop('required',true);
		  $("#con_password").removeAttr('readonly');
		 
	  }else{
		  $('#password').val('');

		  $("#password").prop('required',false);
		  $("#password").attr('readonly');

		  $("#con_password").prop('required',false);
		  $("#con_password").attr('readonly');
	  }
}
</script>