
<?php 
	$cancel_url=$this->url(array(
			'module'=>'rsvacl',
			'controller'=>'usertype',
			'action'=>'index',
		));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate('EDIT_USER_TYPE');?></title>
 <!-- START PAGE CONTENT -->
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-pencil-alt"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("EDIT_USER_TYPE")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
			<div class="col-sm-8">
				<form class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
					<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('USER_TYPE')?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	<input class="form-control"  type="text" required="true" name="user_type" id="user_type" placeholder="User Type" 
												 value="<?php echo $this->usertype['user_type'];?>"
												missingMessage="Invalid User type!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('PARENT_NAME')?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	<select class="form-control"  class='fullside' name="parent_id"  id="parent_id" 
							 missingMessage="Invalid Parent Name!" > 
							 	<?php foreach ($this->usertype_list as $key => $ust) : ?>
									<option value="<?php echo $key;?>"  <?php if($this->usertype['parent_id'] == $key) echo 'selected';?> ><?php echo $ust;?></option>
								<?php endforeach;?>																																
								</select> 
		                   </div>
		                </div>
		                <div class="text-right">
                          	<input class="btn btn-primary black"  type="button" value="<?php echo $tr->translate('GO_BACK');?>" label="<?php echo $tr->translate('GO_BACK');?>" id="back" onclick="window.location = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>"usertype",'action'=>'index'),null,true); ?>';" />
						<input class="btn btn-primary black"  type="submit" value="<?php echo $tr->translate('SAVE');?>" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" />						
	                </div>
	                <input type="hidden" name="user_type_id" value="<?php echo $this->user_edit['id'];?>" />
	             </form>
			</div>
