<?php //sr
	  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
	
	  $home=$this->url(array('module'=>'home','controller'=>'index','action'=>'index'), null, true);
	  $registrar=$this->url(array('module'=>'registrar','controller'=>'register','action'=>'index'), null, true);
	  $foundation=$this->url(array('module'=>'foundation','controller'=>'register','action'=>'index'), null, true);
	  $gep=$this->url(array('module'=>'gep','controller'=>'studentstudy','action'=>'index'), null, true);
	  $accounting=$this->url(array('module'=>'accounting','controller'=>'fee','action'=>'index'), null, true);
	 // $gep=$this->url(array('module'=>'gep','controller'=>'studentstudy','action'=>'index'), null, true);
	  //$gep=$this->url(array('module'=>'gep','controller'=>'gep','action'=>'index'), null, true);
	  $report=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'index'), null, true);
	  $global=$this->url(array('module'=>'global','controller'=>'group','action'=>'index'), null, true);
	  $kidergarten=$this->url(array('module'=>'kindergarten','controller'=>'kindergarten','action'=>'index'), null, true);
	  $reference_path=$this->url(array('module'=>'analysis','controller'=>'query','action'=>'index'), null, true);
	  $backup=$this->url(array('module'=>'backup','controller'=>'index','action'=>'index'), null, true);
      $user=$this->url(array('module'=>'user','controller'=>'index','action'=>'index'), null, true);
      $acl=$this->url(array('module'=>'rsvacl','controller'=>'index','action'=>'index'), null, true);
      $setting=$this->url(array('module'=>'setting','controller'=>'index','action'=>'index'), null, true);
      $library=$this->url(array('module'=>'library','controller'=>'index','action'=>'index'), null, true);
      $module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
	  
	  $session_user=new Zend_Session_Namespace('authstu');
	  $level=$session_user->level;
	  
	  $url_logo = $this->baseUrl()."/images/cam-app-logo.png";
	  $url='';
// 	  $item_arr=array(
// 	  '#'=>'<li class="link">
// 	  		<a title="ទំព័រដើម" href="'.$home.'">
// 	  		<img style="max-height:45px" src="'.$url.'"<span class="icon_menu"></a>
// 	  		</li>',
// 	   'index'=>'<li class="link">
// 							<a title="ទំព័រដើម" href="'.$home.'">
// 								<span class="icon_menu"><i class="fa fa-home" aria-hidden="true"></i></span><br />&nbsp;&nbsp;&nbsp;&nbsp;'.$tr->translate("HOME_PAGE").'&nbsp;&nbsp;&nbsp;
// 							</a>
// 						</li>',	  
// 	  'registrar'=>'<li class="link">
// 						<a title="ការិ.ចុះឈ្មោះ" href="'.$registrar.'">
// 							<span class="icon_menu"><i class="fa fa-graduation-cap" aria-hidden="true"></i></span><br />'.$tr->translate("REGISTRATION").'
// 						</a>
// 				  </li>',
// 	  'global'=>'<li class="link">
// 	  		<a title="ព័ត៏មានផ្សេងៗ" href="'.$global.'">
// 	  		<span class="icon_menu"> <i class="fa fa-users" aria-hidden="true"></i></span><br />'.$tr->translate("OTHER_INFOMATION").'
// 	  		</a>
// 	  		</li>',
// 	  'foundation'=>'<li class="link">
// 	  		<a title="ការិយាល័យរដ្ឋបាល" href="'.$foundation.'">
// 	  		<span class="icon_menu"><i class="fa fa-university" aria-hidden="true"></i><br /></span>'.$tr->translate("ADMINISTRATION").'
// 	  		</a>
// 	  		</li>',
	
	  
// 	  	 'accounting'=>'<li class="link">
// 						<a title="ការិយាល័យគណនេយ្យ" href="'.$accounting.'">
// 							<span class="icon_menu"><i class="fa fa-money" aria-hidden="true"></i></span><br />'.$tr->translate("ACCOUNTING").'
// 						</a>
// 					</li>',
// 	  	 'library'=>'<li class="link">
// 				  		<a href="'.$library.'">
// 				  			<span class="icon_menu"><i class="fa fa-book" aria-hidden="true"></i><br /></span>'.$tr->translate("LIBRARY").'
// 				  		</a>
// 	  				</li>',
// 		//}
// 	    'allreport'=>'<li class="link">
// 						<a title="របាយការណ៏" href="'.$report.'">
// 							<span class="icon_menu"><i class="fa  fa-file-text" aria-hidden="true"></i></span><br />'.$tr->translate("REPORT").'
// 						</a>
// 					   </li>',
// 	  	 'rsvacl'=>'<li class="link">
// 				  		<a title="acl" href="'.$acl.'">
// 				  		<span class="icon_menu"> <i class="fa  fa-cog" aria-hidden="true"></i></span><br />'.$tr->translate("ACL").'
// 				  		</a>
// 				  		</li>',
// 	  	'setting'=>'<li class="link">
// 	  	<a title="ការកំណត់ផ្សេងៗ" href="'.$setting.'">
// 	  	<span class="icon_menu"><i class="fa  fa-cogs" aria-hidden="true"></i></span><br />'.$tr->translate("SRMS_SETTING").'
// 	  	</a>
// 	  	</li>',
	 
// 	  );
	  $icon = array(
	  		'home'=>'<i class="fa fa-home" aria-hidden="true"></i>',
	  		'registrar'=>'<i class="fa fa-money" aria-hidden="true"></i>',
	  		'global'=>'<i class="fa fa-users" aria-hidden="true"></i>',
	  		'foundation'=>'<i class="fa fa-desktop" aria-hidden="true"></i>',
	  		'accounting'=>'<i class="fa fa-money" aria-hidden="true"></i>',
	  		'stock'=>'<i class="fa fa-suitcase" aria-hidden="true"></i>',
	  		'library'=>'<i class="fa fa-book" aria-hidden="true"></i>',
	  		'allreport'=>'<i class="fa  fa-file-text" aria-hidden="true"></i>',
	  		'rsvacl'=>'<i class="fa  fa-cog" aria-hidden="true"></i>',
	  		'setting'=>'<i class="fa  fa-cogs" aria-hidden="true"></i>',
	  		'mobileapp'=>'<i class="fa fa-apple" aria-hidden="true"></i>',
	  		);
// 	if($level>2){
// 		unset($item_arr['accounting']);
// 		unset($item_arr['rsvacl']);
// 	}  
	  
	$module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
	$session_user=new Zend_Session_Namespace('authstu');
	$arr_module = $session_user->arr_module;
	$menuleft=array();
	$class='link';
	if(!empty($arr_module)){
		foreach ($arr_module as $rs){
			if($rs==$module){
				$class='current';
			}else{$class='link';
			}
			
			$controller = 'index';
			$label="";
			
			if($rs=='home'){
				$controller='index';
				$label="HOME_PAGE";
			}
			
			if($rs=='rsvacl'){
				$controller='user';
				$label="ACL";
			}
			elseif($rs=='setting'){
				$controller='database';
				$label="SETTING";
			}
			elseif($rs=='accounting'){
				$controller='fee';
				$label="ACCOUNTING";
				
			}
			elseif($rs=='foundation'){
				$controller='register';
				$label="ADMINISTRATION";
			}
			elseif($rs=='global'){
				$controller='group';
				$label="OTHER_INFOMATION";
			}
			elseif($rs=='registrar'){
				$controller='register';
				$label="REGISTRAR";
			}
			elseif($rs=='allreport'){
				$controller='allstudent';
				$label="ALL_REPORT";
			}
			elseif($rs=='library'){
				$controller='index';
				$label="library";
			}
			elseif($rs=='mobileapp'){
				$controller='index';
				$label="mobileapp";
			}
			elseif($rs=='stock'){
				$controller='index';
				$label="ORIGINAL_PRODUCT";
			}
			
			
			$url =$this->url(array('module'=>$rs,'controller'=>$controller,'action'=>'index'), null, true); ;
			$menuleft[$rs]="<li class='$class'><a href='$url'><span class='icon_menu'>$icon[$rs]</span><br />".$tr->translate(strtoupper($label))."</a></li>";
		}
	}
	
?>  
<div id="menu">
	<ul>
		<li >
			<a ><img src="<?php echo $url_logo;?>" style="max-height:45px"  /></a>
		</li>
		<?php
		$session_user=new Zend_Session_Namespace('authstu');
		$modules_access = $session_user->arr_module;
			foreach($menuleft as $key=>$value){
					if($module==$value){
						echo str_replace('link', 'current',$value);
					}
					else{
						echo $value;
					}
			} 
		?>
		<li style="float: right;">
			<a href="" class="langiconen" onclick="changeLange(2);"></a>
		</li>
		<li style="float: right;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
		<a href="" class="langiconkh" onclick="changeLange(1);"></a>
		</li>
	</ul>
</div>

<script>	
var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
function changeLange(lang){
	dojo.xhrPost({
		url: url_changelang,
	    content :{ 
			    'lange':lang,
		},	
		handleAs:"json",
		load: function(data) {
			location.reload();
		},
		error: function(err) {
			
		}
	});
}
	</script>