<?php 
$session_user=new Zend_Session_Namespace('authstu');
$username = $session_user->first_name;
$them_style =  $session_user->theme_style;
$user_id = $session_user->user_id;
$login_part = $this->baseUrl();
$session_t=new Zend_Session_Namespace('authteacher');
$teacher_id = $session_t->teacher_id;

	if(empty($user_id)){
		if(empty($teacher_id)){
			Application_Form_FrmMessage::redirectUrl('/');	
		}
	}
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = $this->baseUrl();
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
	
	$session_user=new Zend_Session_Namespace('authstu');
	$arr_module = $session_user->arr_acl;
	$user_id = $session_user->user_id;
	if(empty($user_id)){
		Application_Form_FrmMessage::redirectUrl("/");
	}
	if(empty($username)){
		$username =  $session_t->teacher_name;
	}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link rel="stylesheet" href="<?php echo $base_url;?>/css/template.css"/>
	<link rel="stylesheet" href="<?php echo $base_url;?>/css/font-awesome.min.css"/>
	<link href="<?php echo $base_url;?>/cssmenu/template.css" media="screen" rel="stylesheet" type="text/css">
	<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.8.3.min.js"></script>
<?php //if($module!='home'){?>
	<script src="<?php echo $base_url;?>/js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>/js/dojo-1.6.1/dijit/themes/soria/soria.css"/>
	<script src="<?php echo $base_url;?>/js/help.js"  type="text/javascript"></script>
	<script src="<?php echo $base_url;?>/js/pdbs_js.js"  type="text/javascript"></script>

	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.js"> </script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.tablesorter.pager.js"> </script>
<?php //}?>
	<?php if($module=='allreport' OR $action=='allreports' OR $action=='studentnearlyendservice' OR 
			$action=='studentpaymentlate' OR $controller=='allreports' OR $controller=='rptproductsold' OR
			$controller=='studentnearlyendservice' OR $controller=='studentpaymentlate' ){?>
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/tableExport.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jquery.base64.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/html2canvas.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/sprintf.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/jspdf.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/base64.js"></script> 
      <?php } ?>	
      
	<link rel="shortcut icon" href="<?php echo $base_url;?>/images/icon.ico" type="image/x-icon"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<style type="text/css">
*{ padding:0;margin:0;}
    html, body { width: 100%; height: 100%; margin: 0; padding:0;margin-top: -2px; }
		.btn{
			height: 40px;
			min-width: 100px;	
		}
		.fullside{ width:100%; height: 30px;}
		.full{ width:100%;}
		body, html {font-size:98%; font-family:'Khmer OS Battambang'}
        /*body, html { font-family:helvetica,arial,sans-serif; font-size:95%; }*/
		*{ padding: 0; margin: 0;}
		fieldset{ font-family: inherit;}
		.addsign{color: #fff;
			    background: #008;
			    padding: 2px 19px;}
	</style>	
</head>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.NumberTextBox');
	
	dojo.require("dijit.form.CheckBox");     
	dojo.require("dojo.number");
	////dojo.require('dojox.form.BusyButton');
dojo.require("dijit.form.RadioButton");
	dojo.require("dijit.Dialog");
	
	dojo.require("dijit.layout.BorderContainer");
	dojo.require("dijit.layout.TabContainer");
	dojo.require("dijit.layout.AccordionContainer");
	dojo.require("dijit.layout.ContentPane");
	dojo.require("dojo.parser");
</script>
    <?php 
	    $class='soria';
	    $them_style='soria';
		$level=$session_user->level;
		if($level!=1 AND $module=='rsvacl'){
			Application_Form_FrmMessage::redirectUrl("/home");	
		}
    ?>
    <body class="<?php echo $class;?>" ><!-- oncontextmenu="return false;" -->
        <table style="height: 100%;" width="100%" >
            <tr height="45px" >
            	<td colspan="2" valign="top"> <?php echo $this->render('header.phtml')?>
            	 	<p style="font-size:13px !important; ">
				    <span style="padding-left: 3px;padding-right: 3px;float: left; font-weight:600;"><?php echo $tr->translate("USING_BY");?>&nbsp;&nbsp;<a style="color:red;" href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>" ><?php echo $username;?></a></span>  
					<a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>">&nbsp; | &nbsp;<?php echo $tr->translate("SIGN_OUT");?><i class="fa fa-sign-out" aria-hidden="true"></i></a>
	                 <?php if($action=='index' AND $module!='report' AND $module!='home' AND $controller!='studentnearlyendservice' AND $controller!='studentpaymentlate' AND $controller!='studentpaymentlate' AND $module!='allreport'  ){?>
	                 <a class='add-link addsign' style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'add'),null,true); ?>"><?php echo $tr->translate('ADD');?>&nbsp;<i class="fa fa-plus-square" aria-hidden="true"></i></a>
					<?php }elseif($action=='add' OR $action=='edit' OR $action=='copy' OR $action=='view' OR $module=='report'){?>
					 <span style="padding-left: 3px;padding-right: 3px; float: right; font-weight:600;"><a class='add-link addsign' href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i><?php echo $tr->translate('GO_BACK');?></a></span>
					<?php }?>
					</p>
            	</td>
            </tr>
             <tr>
             	<?php if($module!='home'){?>
            	<td width="200px" valign="top" style="border:1px solid #ccc;">
            		<?php 
            		if(!empty($arr_module)){
            			echo $this->render('menuleft.phtml');
            		}
            		if(!empty($teacher_id)){
            	?>
            		<div id="header-left">
						<ul><li><a href="<?php echo $this->url(array("module"=>'foundation','controller'=>'teacherscore','action'=>'index'));?>">Teacher Score</a></li>
						</ul>
					</div>
					<?php }?>
            	</td>
            	<?php }?>
            	<td valign="top" style="border:1px solid #ccc; background:#ccd9ff; width: 1000px;">
	            	<?php if($module=='allreport' AND $action!='index' AND $action!='rpt-certificate' ){?>
						<!-- 
						<div class="menureport">
							<ul>
								<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
								<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
								<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
							</ul>
						</div>
						 -->
						
						<div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
							<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
								<i class="fa fa-print"></i>
							</div>
							<div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
							<div class="ptss__settings">
								<div class="ptss__single-setting" id="ptss__layout">
									<div class="ptss__setting-control">
										<div class="ptss__layout-wrapper">
											<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
											<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
											<a class="qButton excel" href="#"  title="<?php echo $tr->translate("Export");?>"  onclick="exportExcel();"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
										</div>
										
									</div>
								</div>
							</div>
						</div>
						<div style="clear:both;"></div>
						<?php }?>
            			<?php 
							$db = new Application_Model_DbTable_DbUsers();
	            			$rs = $db->getAccessUrl($module,$controller,$action);

	            			
	            			echo $this->layout()->content;
	            			
							/*
	            			if(!empty($rs) OR $action=='changepassword'){

	            				echo $this->layout()->content;
	            			}else{
	            				echo $this->render('pagenotfund.phtml');
	            			}
	            			*/
            			 ?>
            	</td>
            </tr>
             <tr height="30px" style="border:1px solid #ccc;background:#B9B9CC; color: #008;">
             	<td align="center" colspan="2" valign="middle">
             		<marquee behavior="scroll" direction="left" onmouseout="this.start()" onmouseover="this.stop()" scrollamount="5" style="">Copyright © Cam App Technology,All Rights Reserved.
             		Developed by Cam App Technology | <?php echo $tr->translate("អភិវឌ្ឍន៍ដោយ ខេម អ៊ែប តិចណូឡូជី");?>
					Tel : 085 911 912 | 070 75 64 57</marquee>
             	</td>
             </tr>
        </table>
    </body>
    
    <iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php if($module=='allreport' AND $action!='index' OR $action='allreports' OR $action='studentnearlyendservice' OR $action='studentpaymentlate'){?>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1100, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
jQuery(function () {
	'use strict';
	
	jQuery(".ptss__toggle-btn").click(function () {	
		jQuery('.js-ptss-frame').toggleClass('is-opened');
	});
	
	jQuery('.ptss__layout-wrapper > div').click(function(){
		
		jQuery(this).closest('.ptss__setting-control').find('.ptss__layout-wrapper').removeClass('is-selected');
		
		jQuery(this).parent().addClass('is-selected');
		
		if( jQuery(this).hasClass('ptss__layout-box--wide') ) {
			
			jQuery('body').removeClass('boxed');
			jQuery('#ptss__boxed-bg').hide();
			
			jQuery('body').removeClass('bg1').removeClass('bg2').removeClass('bg3').removeClass('bg4');
			
			jQuery('#ptss__boxed-backgrounds span').removeClass('is-selected');
			
		} else {
			
			jQuery('body').addClass('boxed');
			jQuery('#ptss__boxed-bg').show();
			
		}
		
	});
})
</script>
<?php  }?>
</html>

