<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
	
	$session_user=new Zend_Session_Namespace('auth_travel');
	$username = $session_user->first_name;
	$them_style = 'soria'; //$session_user->theme_style;
	
	$session_lang=new Zend_Session_Namespace('lang');
	
	$lang_id = $session_lang->lang_id;//for creat session
	if(empty($lang_id)){
		$session_lang->lang_id=1;
	}
	
		
?>
<?php if($module!='default'){
	if (empty($session_user->user_id)){
		//Application_Form_FrmMessage::redirectUrl("/");
	}
	?>
<html>
<head>
	<?php if($module!='home'){?>
	<?php }?>
	<?php if($module!='home'){?>
    <?php  } ?>
     <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        
        <script src="<?php echo $this->baseUrl()."/templates/assets/"?>jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/templates"?>/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/templates"?>/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
        
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/templates"?>/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl()."/templates"?>/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
        
        <!-- Plugins css-->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()."/templates"?>/assets/plugins/clockface/css/clockface.css"/>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()."/templates"?>/assets/plugins/bootstrap-datepicker/css/datepicker3.css"/>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()."/templates"?>/assets/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css"/>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()."/templates"?>/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css"/>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()."/templates"?>/assets/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css"/>
         
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css" rel="stylesheet" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/switchery/switchery.min.css">
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
        <?php /*?>
       
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet">
		<link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css" rel="stylesheet">
		<link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
		<link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/clockpicker/css/bootstrap-clockpicker.min.css" rel="stylesheet">
		<link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <?php */?>
         <!-- jvectormap -->
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/jvectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
        
        <!--Morris Chart CSS -->
		<link rel="stylesheet" href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/morris/morris.css">
        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/css/bootstrap.min.css" rel="stylesheet">
        <!-- MetisMenu CSS -->
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/css/metisMenu.min.css" rel="stylesheet">
        <!-- Icons CSS -->
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/css/icons.css" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/css/style.css" rel="stylesheet">
	<!-- export library -->

    <link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/images/icon.ico" type="image/x-icon"/>
    
     <!-- DataTables -->
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/buttons.bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/responsive.bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/scroller.bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/dataTables.colVis.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/fixedColumns.dataTables.min.css" rel="stylesheet" type="text/css"/>
    
    <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/jquery-2.1.4.min.js"></script>
    <style type="text/css">
        .navbar-default .navbar-nav>li>a {
            color: #fff;
        }
        .navbar-default .navbar-nav>.open>a, .navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
            color: #fff;
        }
        .navbar-default .navbar-nav>li>a:focus, .navbar-default .navbar-nav>li>a:hover {
            color: #fff;
        }
        
        #page-right-content {
            background-color: #FBFCFC;
        }
    </style>
</head>

  <body>
  	 <div id="page-wrapper">

            <!-- Top Bar Start -->
            <div class="topbar">

                <!-- Top navbar -->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container" style="background: #5a5a5a   !important;">
                    	<div class="col-lg-2 col-sm-2 text-center">
	                        <a href="<?php echo $this->baseUrl()."/employee";?>" class="logo">
	                            <img src="<?php echo $this->baseUrl()."/images/lang/logo.png";?>" alt="logo" class="logo-lg" />
	                        </a>
	                        
	                    </div>
	                    <div class="col-lg-4 col-sm-4 ">
	                    	<!-- Mobile menu button -->
                            <div class="pull-left">
                                <button type="button" class="button-menu-mobile visible-xs visible-sm">
                                    <i class="fa fa-bars"></i>
                                </button>
                                <span class="clearfix"></span>
                            </div>
	                    	<h2><?php //echo $tr->translate('ADMINISTRATOR');?></h2>
	                    	
	                    </div>
                        <div class="col-lg-6 col-sm-6">
                            <!-- Top nav Right menu -->
                            <ul class="nav navbar-nav navbar-right top-navbar-items-right pull-right">
                            	 <li class="dropdown top-menu-item-xs">
                                    <a href="#" data-target="#" class="dropdown-toggle menu-right-item" data-toggle="dropdown" aria-expanded="true">
                                        <i class="mdi mdi-earth"></i> <?php if($session_lang->lang_id==1){ echo $tr->translate('ENGLISH');}else{ echo $tr->translate('KHMER');}?>
                                    </a>
                                    <ul class="dropdown-menu p-0 dropdown-menu-lg">
                                    	<li>
                                            <a href="javascript:void(0);" onclick="changeLange(2);" class="list-group-item text-center">
                                               <?php echo $tr->translate('KHMER')?>
                                            </a>
                                        </li>
                                         <li>
                                            <a href="javascript:void(0);" onclick="changeLange(1);" class="list-group-item text-center">
                                               <?php echo $tr->translate('ENGLISH')?>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="dropdown top-menu-item-xs">
                                    <a href="" class="dropdown-toggle menu-right-item profile" data-toggle="dropdown" aria-expanded="true"><img src="<?php echo $this->baseUrl()."/images/profile.jpg";?>" alt="user-img" class="img-circle"> </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'changepassword')); ?>"><i class="ti-settings m-r-10"></i> <?php echo $tr->translate('Change Password')?></a></li>
                                        <li class="divider"></li>
                                        <li><a href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>"><i class="ti-power-off m-r-10"></i> <?php echo $tr->translate('Logout')?></a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div> <!-- end container -->
                </div> <!-- end navbar -->
            </div>
            <!-- Top Bar End -->
            <!-- Page content start -->
            <div class="page-contentbar" style="background: #f5c368c4;">
            <?php echo $this->render('menuleft.phtml')?> 
              <?php 
              	/*
	              	$db = new Application_Model_DbTable_DbUsers();
            		$rs = $db->getAccessUrl($module,$controller,$action);
            		if(!empty($rs) OR $action=='changepassword'){
            				
             			echo $this->layout()->content;
            		}else{
            			echo $this->render('pagenotfund.phtml');
            		}
            	*/	
              	echo $this->layout()->content;
			?>

  
   			 </div>
            <!-- end .page-contentbar -->
    </div>
    <!-- End #page-wrapper -->
	<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
	<div class="overlay">
		<div class="overlay-load">
			<div class="overlay-msg">
		    </div>
		</div>
	</div>
 	<!-- js placed at the end of the document so the pages load faster -->

        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/metisMenu.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/jquery.slimscroll.min.js"></script>
       
        <!-- Datatable js -->
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/dataTables.bootstrap.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/dataTables.buttons.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/buttons.bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/jszip.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/pdfmake.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/vfs_fonts.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/buttons.html5.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/buttons.print.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/dataTables.keyTable.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/dataTables.responsive.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/responsive.bootstrap.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/dataTables.scroller.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/dataTables.colVis.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/datatables/dataTables.fixedColumns.min.js"></script>
        
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.min.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/select2/js/select2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/switchery/switchery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/parsleyjs/parsley.min.js"></script>
        
         <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/moment/moment.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/timepicker/bootstrap-timepicker.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
     	<script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
     	<script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/clockpicker/js/bootstrap-clockpicker.min.js"></script>
     	<script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/plugins/summernote/summernote.min.js"></script>
        
        
        
        <!-- init -->
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/pages/jquery.datatables.init.js"></script>
        
          <!-- form advanced init js -->
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/pages/jquery.form-advanced.init.js"></script>
        
        <!-- App Js -->
        <script src="<?php echo $this->baseUrl()."/templates/";?>assets/js/jquery.app.js"></script>
        
         
        
        <script>
			function loading(){
			    document.getElementsByClassName("overlay")[0].style.display="block";
			}
			function closeloading(){
			    document.getElementsByClassName("overlay")[0].style.display="none";
			}
			var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
			function changeLange(lang){
				jQuery.ajax({
					url: url_changelang,
					type: "post",
					data:{'lange':lang},
					success: function(data){
						location.reload();
					},
					error:function(err){
					}
				});
			}
		</script>
        <?php if($module=='report' AND $controller!='index'){?>
		<script type="text/javascript">
		function doPrint() {
			window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
		    window.frames["print_frame"].window.focus();
		    window.frames["print_frame"].window.print();
		    hideDialog();
		}
		function hideleft(){
			(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
		}
		function preview()
		{ 
		  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
		      disp_setting+="scrollbars=no,width=1100, height=700, left=100, top=25"; 
		  var content_vlue = document.getElementById("divPrint").innerHTML; 
		  var docprint=window.open("","",disp_setting); 
		   docprint.document.open(); 
		   docprint.document.write('<html><head>'); 
		   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
		   docprint.document.write(content_vlue);          
		   docprint.document.write('</center></div></html>'); 
		   docprint.document.close(); 
		   docprint.focus(); 
		}
		function exportExcel(){
			$('#exportExcel').tableExport({type:'excel',escape:'false'});
		}
		</script>
		<?php }?>
    </body>
</html>
<?php }else{
// 		echo $this->render('headerfront.phtml');
		echo $this->layout()->content;
// 		echo $this->render('footerfront.phtml');
}?>