	<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$moduless = $request->getModuleName();
	$controllersss=$request->getControllerName();
	$baseurl  = $this->baseUrl();
	
	$dbuser = new Application_Model_DbTable_DbUsers();
	
	$session_user=new Zend_Session_Namespace('auth_flower');
	$arr_module = $session_user->arr_acl;
	$username = $session_user->first_name;
	
	$ReportAction = $dbuser->getArrAclReport($session_user->level);
	
	$userinfo="";
	if (!empty($session_user->user_id)){
	$userinfo = $dbuser->getUserInfomation($session_user->user_id);
	}
	$menu = array();
	$module = '';
	$controller=array();
	$newarray=array();
	if(!empty($arr_module)){
		foreach ($arr_module as $key => $rs){
			$lblcontroller = $rs['controller'];
// 			if($rs['module']=='report' AND $rs['controller']!='index'){
// 				$lblcontroller='REPORT';
// 				continue;
// 			}
			if($rs['module']=='degree' AND $rs['controller']=='index'){
				$lblcontroller='DEGREE';
			}
			if($rs['module']=='report' AND $rs['controller']=='index'){
				$lblcontroller='REPORT';
			}
			if($rs['module']=='requestscholarship' AND $rs['controller']=='index'){
				$lblcontroller='REQUESTSCHOLARSHIP';
			}
			if($rs['module']=='requestscholarship' AND $rs['controller']=='program'){
				$lblcontroller='PROGRAM STUDY';
			}
			if($module!=$rs['module']){
				$newarray= array($rs['controller']=>$tr->translate(strtoupper($lblcontroller)));
				$menu[$rs['module']]= $newarray;
			}else{
				$newarray= array_merge($newarray,array($rs['controller']=>$tr->translate(strtoupper($lblcontroller))));
			    $menu[$rs['module']] = $newarray;
			}
			$module=$rs['module'];
		}
	}
	$arr_param_menu = $menu;
	$dc=new Application_Model_Decorator();
	?>
	<?php 
	$array_icon = array(
			'home'=>'<i class="ti-home"></i>',
			'requestscholarship'=>'<i class="ti-write"></i>',
			'degree'=>'<i class="ti-layout-tab"></i>',
			'report'=>'<i class="ti-desktop"></i>',
			'rsvacl'=>'<i class="ti-user"></i>',
			'setting'=>'<i class="ti-settings"></i>',
	);
	$arr_module = $session_user->arr_module;
	$arr_acl = $session_user->arr_acl;
	?>
	 <!--left navigation start-->
                <aside class="sidebar-navigation">
                    <div class="scrollbar-wrapper">
                        <div>
                            <button type="button" class="button-menu-mobile btn-mobile-view visible-xs visible-sm">
                                <i class="mdi mdi-close"></i>
                            </button>
							<div class="buttun-booking">
								<a class="btn btn-primary top-make-booking" href="<?php echo $this->baseUrl()."/requestscholarship/index/add";?>"><?php echo $tr->translate("ADD REQUESTSCHOLARSHIP");?></a>
							</div>
                            <!-- Left Menu Start -->
                            <ul class="metisMenu nav" id="side-menu">
								<?php if(!empty($arr_module)){ foreach ($arr_module as $rs){
			                		$url =$this->url(array('module'=>$rs,'controller'=>'index','action'=>'index'), null, true);
			                		if ($rs=="home"){
			                			$title=$tr->translate("DASHBOARD");
			                		}else{
			                			$title=$tr->translate(strtoupper($rs));
			                		}
			                	?>
			                	<?php if ($rs=="report"){?>
			                	<li <?php if ($moduless==$rs){?>class="active"<?php }?>>
			                	 <a href="javascript: void(0);" aria-expanded="true"><?php echo $array_icon[$rs];?> <?php echo $title;?> <span class="fa arrow"></span></a>
			                		<ul class="nav-second-level nav" aria-expanded="true">
			                			<?php if (!empty($ReportAction)) foreach ($ReportAction as $rep){
			                				$urlsub = $this->url(array('module'=>$rep['module'],'controller'=>$rep['controller'],'action'=>$rep['action']), null, true);
			                				?>
			                			<li><a href="<?php echo $urlsub;?>"><?php echo $tr->translate(strtoupper($rep['label']));?></a></li>
			                			<?php }?>
			                		</ul>
			                	</li>
			                	<?php }else{?>
                                <li <?php if ($moduless==$rs){?>class="active"<?php }?>>
                                	<?php 
                                		$count= count($arr_param_menu[$rs]);
                                		if ($count==1){
                                			foreach ($arr_param_menu[$rs] as $key => $sub){
                                				$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
                                				?>
                                				<a href="<?php echo $urlsub;?>" aria-expanded="true"><?php echo $array_icon[$rs];?> <?php echo $title;?></a>
                                	<?php 
                                				}
                                		}else if ($count >1){
                                	?>
		                                    <a href="javascript: void(0);" aria-expanded="true"><?php echo $array_icon[$rs];?> <?php echo $title;?> <span class="fa arrow"></span></a>
		                                    <?php if (!empty($arr_param_menu[$rs])){?>
		                                    <ul class="nav-second-level nav" aria-expanded="true">
		                                    	<?php  foreach ($arr_param_menu[$rs] as $key => $sub){
							                       	$urlsub = $this->url(array('module'=>$rs,'controller'=>$key,'action'=>'index'), null, true);
							                       	?>
		                                        <li><a href="<?php echo $urlsub;?>"><?php echo $sub;?></a></li>
		                                        <?php }?>
		                                    </ul>
		                                     <?php }?>
                                     <?php } ?>
                                </li>
                                <?php }
								}?>
                				 <?php }?>
                            </ul>
                        </div>
                    </div><!--Scrollbar wrapper-->
                </aside>
                <!--left navigation end-->
                
		