<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('Edit Location'));
echo $this->headTitle();
$row=$this->row;
?>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-star	"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Edit Location")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/location/location/index";?>"><?php echo $tr->translate("GO_BACK")?></a>
    			</div>
    		</div>
    		
			<div class="col-sm-8">
				<form id="frm" class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
					<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Location Name')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	<input class="form-control"  type="text" required="true" name="location_name" id="location_name" placeholder="<?php echo $tr->translate('location name')?>" value="<?php echo $row['locationName']?>"/>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('SERVICE_TYPE')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	 <select class="form-control select2" id="service_type"  name="service_type"  > 
		                 	  		<?php if(!empty($this->service_type)) foreach ($this->service_type As $servic){?>
		                   			<option value="<?php echo $servic['id']?>" <?php if($servic['id']==$row['serviceId']) echo "selected='selected'"?>><?php echo $servic['name']?></option>
								    <?php }?>
								</select> 
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Country Name')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	 <select class="form-control select2" id="country_name"  name="country_name"  > 
		                   			<option value="1" <?php if($row['countryId']==1) echo "selected='selected'"?>><?php echo $tr->translate('CAMBODIA')?></option>
							</select> 
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Order By')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	<input class="form-control"  type="text"  name="order_by" id="order_by" value='<?php echo $row['orderRing']?>' placeholder="<?php echo $tr->translate('Order By')?>"/>
	                   </div>
	                </div>
	             <!-- 
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('DESCRIPTION')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                   		<textarea class="form-control" rows="5" id="description" name="description"><?php echo $row['orderRing']?></textarea>
	                   </div>
	                </div>
	                 -->   
                    <div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-right">
								<input class="btn btn-primary black save" name="save_close"  id="save_close" type="submit"  label="<?php echo $tr->translate('SAVE_CLOSE');?>" value="<?php echo $tr->translate('SAVE_CLOSE');?>" id="submitButton" />
			                </div>
	                    </div>
                    </div>
	               
	              </form>
			</div>
		</div>
	</div>
</div>
 
 
 <script type="text/javascript">
	$('#frm').submit(function() {
		service_type = $("#service_type").val();
	    if(service_type=='' || service_type==-1){
	        alert("<?php echo $tr->translate('Select Service')?>");
	        $('#service_type').select2('open');
	        return false;
	    }
		var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
		if (r == true) {
		    return true;
		} else {
		   return false;
		}
	});
</script>