<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("Location List")); 
	echo $this->headTitle();
?>	

<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'index','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'index','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'index','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>

<style>
	#grid{
		margin: 0 auto;
	}
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-user"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Location List")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    				<div class="buttun-block">
						<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/location/location/add";?>"><?php echo $tr->translate("Add Location")?></a>
					</div>
    			</div>
    		</div>
			<div class="col-sm-12">
				<div class="card-box">
					<form name="frmlist_users" action=""  method="post">
						<div class="form-group">
                            <div class="col-md-3">
                                <input type="text" class="form-control" name="adv_search" id="adv_search"  placeholder="<?php echo $tr->translate("SEARCH_INFO");?>" value='<?php echo $this->search['adv_search'];?>'>
							</div>
							<div class="col-md-3">
							     <select class="form-control select2" id="service_type"  name="service_type" required > 
							        <option value="0"><?php echo $tr->translate('Select Service')?></option>
		                 	  		<?php if(!empty($this->service_type)) foreach ($this->service_type As $servic){?>
		                   			<option value="<?php echo $servic['id']?>" <?php if($this->search['service_type']==$servic['id']) echo 'selected="selected"';?>><?php echo $servic['name']?></option>
								    <?php }?>
								</select> 
							</div>
                            <div class="col-md-3">
                                <select class="form-control select2" id="status"  name="status"  > 
		                 	  		<option value="-1"><?php echo $tr->translate('STATUS')?></option>
		                   			<option value="1" <?php if ($this->search['status']==1){ echo 'selected="selected"';}?>><?php echo $tr->translate('ACTIVE')?></option>
		                   			<option value="0" <?php if ($this->search['status']==0){ echo 'selected="selected"';}?>><?php echo $tr->translate('DEACTIVE')?></option>
								</select> 
							</div>
							<div class="col-md-3">
                                <button class="btn btn-primary " showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
							</div>
                       </div>
					</form>
					<div class="clearfix"></div>
					<?php echo $this->list;?>
				</div>
			</div>
		</div>
	</div>
</div>