<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('Add Testimonial'));
echo $this->headTitle();
?>
<style>
.image-feature img#profile-img-tag {
    margin-bottom: 10px;
        height: 210px;
}
</style>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-star	"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Add Testimonial")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/other/testimonial/index";?>"><?php echo $tr->translate("GO_BACK")?></a>
    			</div>
    		</div>
    		<form name="frm_location" class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<div class="col-sm-8">
					<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Name Of Person')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	<input class="form-control"  type="text" required="true" name="name_person" id="name_person" placeholder="<?php echo $tr->translate('Name Of Person')?> "/>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Position')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	 <select class="form-control select2" id="position"  name="position" required > 
		                 	  		<option value="-1"><?php echo $tr->translate('Select Position')?></option>
		                   			<option value="1"><?php echo $tr->translate('Designer Leader')?>  </option>
		                   			<option value="2"><?php echo $tr->translate('Arti Derector')?>  </option>
		                   			<option value="3"><?php echo $tr->translate('Seo & Marketing')?>  </option>
		                   			<option value="4"><?php echo $tr->translate('Web Development')?>  </option>
		                   			<option value="5"><?php echo $tr->translate('IT Programmer')?>  </option>
		                   			<option value="6"><?php echo $tr->translate('Other')?>  </option>
								</select> 
	                   </div>
	                </div>
	                
	                 <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('DESCRIPTION')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                   		<textarea class="form-control" rows="5" id="description" name="description" ></textarea>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"> <?php echo $tr->translate('ORDER_BY')?> :  
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
							<input class="form-control"  type="text"  name="order_by" id="order_by" placeholder="<?php echo $tr->translate('ORDER_BY')?>" value=""/>
	                   </div>
	                </div>
	                 
	                <div class="col-md-8 col-sm-8 col-xs-8">
	                <br/><br/>
	                  </div>
                    <div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
								<input class="btn btn-primary black save" name="save_close"  id="save_close" type="submit" value="<?php echo $tr->translate('SAVE_CLOSE');?>" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="submitButton" />
								<input class="btn btn-primary black save" name="save_new"  id="save_new" type="submit" value="<?php echo $tr->translate('SAVE_NEW');?>" label="<?php echo $tr->translate('SAVE_NEW');?>" id="submitButton" /> 
	                    </div>
                    </div>
			</div>
			<div class="col-sm-4">
				<div class="form-group col-md-12 col-sm-12 col-xs-12 ">
					<label class="control-label " for="first-name"><?php echo $tr->translate('រូបភាពតំណាង')?> </label>
				</div>
				<div class="form-group">
				 	
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                    	<div class="image-feature m-b-10 center-block">
                            <img id="profile-img-tag" src="<?php echo $this->baseUrl()."/images/vehicle_type.png";?>" class=" img-thumbnail m-b-10" alt="profile-image">
	                        <input type="file" id="profile-img" class="filestyle" data-input="false" name="photo" data-buttontext="<?php echo $tr->translate('BROWSE_PHOTO')?>">
	                      </div>
                        </div>
                 </div>
			</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">

$('#frm_location').submit(function() {
	service_type = $("#position").val();
    if(service_type=='' || service_type==-1){
        alert("<?php echo $tr->translate('Select Position')?> ");
        $('#position').select2('open');
        return false;
    }
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
	} else {
	   return false;
	    
	}
});

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>