<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('Edit Testimonial'));
echo $this->headTitle();
$row=$this->row;
//print_r($row);exit();
?>
<style>
.image-feature img#profile-img-tag {
    margin-bottom: 10px;
        height: 210px;
}
</style>
 <!-- START PAGE CONTENT -->
 
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-star	"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Edit Testimonial")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/other/testimonial/index";?>"><?php echo $tr->translate("GO_BACK")?></a>
    			</div>
    		</div>
    		<form name="frm_location" class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<div class="col-sm-8">
					<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Name Of Person')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	<input class="form-control"  type="text" required="true" name="name_person" id="name_person" placeholder="<?php echo $tr->translate('Name Of Person')?> " value="<?php echo $row['person_naem']?>"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Modify Date')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                   		 <div class="input-group">
                                <input type="text" class="form-control" placeholder="mm/dd/yyyy" id="datepicker" name="post_date"  value="<?php echo date("d-m-Y",strtotime($row['modifyDate']))?>">
                                <span class="input-group-addon bg-custom b-0"><i class="mdi mdi-calendar text-white"></i></span>
                            </div> 
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Email')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                     <input type="email" class="form-control"   name="email" id="email" placeholder="<?php echo $tr->translate('Email');?>" value="<?php echo $row['email']?>"/>
	                   </div>
	                </div>
	                
	                 <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Description')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                   		<textarea class="form-control" rows="5" id="description" name="description"><?php echo $row['description']?></textarea>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"> <?php echo $tr->translate('Order By')?> :  
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
							<input class="form-control"  type="text"  name="order_by" id="order_by" placeholder="<?php echo $tr->translate('Order By')?>" value="<?php echo $row['orderBy']?>"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"> <?php echo $tr->translate('STATUS')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                        <select class="form-control select2" id="status"  name="status"  > 
	                   			<option value="1"  <?php if($row['status']==1) echo "selected='selected'"?>><?php echo $tr->translate('ACTIVE')?></option>
	                   			<option value="0"  <?php if($row['status']==0) echo "selected='selected'"?>><?php echo $tr->translate('DEACTIVE')?></option>
							</select>
	                   </div>
	                </div>
	                 <input type="hidden" name="old_pic" id="old_pic" value="<?php echo $row['image']?>" >
	                 <div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-right">
								<input class="btn btn-primary black save" name="save_close"  id="save_close" type="submit" value="<?php echo $tr->translate('Save Close');?>"   id="submitButton" />
			                </div>
	                    </div>
                    </div>
			</div>
			<div class="col-sm-4">
				<div class="form-group col-md-12 col-sm-12 col-xs-12 ">
					<label class="control-label " for="first-name"><?php echo $tr->translate('Image')?> </label>
				</div>
				<div class="form-group">
				 	
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                    	<div class="image-feature m-b-10 center-block">
	                    	<?php 
	                    	  if($row['image']!=''){
	                    	      $img="/images/all/".$row['image'];
	                    	  }else{
	                    	      $img="/images/profile.jpg";
	                    	  }
	                    	?>
                            <img id="profile-img-tag" src="<?php echo $this->baseUrl().$img?>" class=" img-thumbnail m-b-10" alt="profile-image">
	                        <input type="file" id="profile-img" class="filestyle" data-input="false" name="photo" data-buttontext="<?php echo $tr->translate('BROWSE_PHOTO')?>">
	                        
	                      </div>
                        </div>
                 </div>
			</div>
			</form>
 
<script type="text/javascript">

$('#frm_location').submit(function() {
	service_type = $("#position").val();
    if(service_type=='' || service_type==-1){
        alert("<?php echo $tr->translate('Select Position')?> ");
        $('#position').select2('open');
        return false;
    }
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
	} else {
	   return false;
	    
	}
});

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>

 