<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("Testimonial List")); 
	echo $this->headTitle();
?>	

<?php 
	$url_new = $this->url(array('module'=>'other','controller'=>'testimonial','action'=>'add',));
	$url_edit = $this->url(array('module'=>'other','controller'=>'testimonial','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'other','controller'=>'testimonial','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>

<style>
	#grid{
		margin: 0 auto;
	}
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
 <!-- START PAGE CONTENT -->
 
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-user"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Testimonial List")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    				<div class="buttun-block">
						<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/other/testimonial/add";?>"><?php echo $tr->translate("Add Testimonial")?></a>
					</div>
    			</div>
    		</div>
			<div class="col-sm-12">
				<div class="card-box">
					<form name="frmlist_users" action=""  method="post">
						<div class="form-group">
                            <div class="col-md-3">
                                <input type="text" class="form-control" name="adv_search" id="adv_search"  placeholder="<?php echo $tr->translate("SEARCH_INFO");?>" value='<?php echo $this->search['adv_search'];?>'>
							</div>
							<div class="col-md-5 search">
                                     	<div class="input-daterange input-group" id="date-range">
                                          	<input type="text" class="form-control" name="start" value="<?php if (!empty($this->search['start'])){ echo date("d-m-Y",strtotime($this->search['start']));}?>" />
                                            <span class="input-group-addon b-0"><?php echo $tr->translate("to");?></span>
                                            <input type="text" class="form-control" name="end" value="<?php if (!empty($this->search['end'])){ echo date("d-m-Y",strtotime($this->search['end']));}?>" />
                                       </div>
                                   	</div>
                            <div class="col-md-3">
                                <select class="form-control select2" id="status"  name="status"  > 
		                 	  		<option value="-1"><?php echo $tr->translate('STATUS')?></option>
		                   			<option value="1" <?php if ($this->search['status']==1){ echo 'selected="selected"';}?>><?php echo $tr->translate('ACTIVE')?></option>
		                   			<option value="0" <?php if ($this->search['status']==0){ echo 'selected="selected"';}?>><?php echo $tr->translate('DEACTIVE')?></option>
								</select> 
							</div>
							<div class="col-md-1">
                                <button class="btn btn-primary " showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
							</div>
                       </div>
					</form>
					<div class="clearfix"></div>
					<?php echo $this->list;?>
				</div>
			</div>
	 