<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('Add Vehicle Price'));
echo $this->headTitle();
?>
<style>
.form-group {
    margin-bottom: 5px;
}
.form-horizontal .control-label {
    text-align: left;
}
.thumb-xl {
    height: 180px;
    width: 150px;
}
div.browe_photo .input-group {
    display: block;
}
label#error {
    color: #F44336;
}

.aligncenter{
	text-align: center;
	background:#ecba11;
	color:#584509;
}

</style>
<form name="frmlist_users" id="frm" class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" autocomplete="off">
	<div class="col-sm-12 border-botom">
		<div class="col-sm-8">
			<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Add Vehicle Price");?></h4>
		</div>
		<div class="col-sm-4 text-right">
			<input id="backbutton" class="btn btn-primary block" type="button" onclick="window.location = '<?php echo $this->url(array('module'=>'vehicle','controller'=>"index",'action'=>'index'),null,true); ?>';" value="<?php echo $tr->translate('GO_BACK');?>" />
		</div>
	</div>
	<div class="col-xs-2"></div>
	<div class="col-xs-8">
		<div class="form-group">
			<label id="error" class="col-md-12 col-sm-12 col-xs-12 text-center" ></label>
		   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">
				<?php echo $tr->translate("Supplier Name");?>
		   </label>
		   <div class="col-md-7 col-sm-7 col-xs-7">
				<select class="form-control select2" name="supplyerId" id="supplyerId" onchange="getPopupSupplyer();" placeholder="ប្រភេទរថយន្ត" >
					<option value=""><?php echo $tr->translate("Supplier Name");?></option>
					<option value="-1"><?php echo $tr->translate("Add New")?></option>
					<?php if(!empty($this->supplyer)){foreach ($this->supplyer as $rs){?>
					<option value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
					<?php }}?>
				</select>
		   </div>
		</div>
		<div class="form-group">
		   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">
				<?php echo $tr->translate("Vehicle Type");?>
		   </label>
		  <div class="col-md-7 col-sm-7 col-xs-7">
			  <select class="form-control select2" name="vehicleType" id="vehicleType" placeholder="ប្រភេទរថយន្ត" onchange="getPopupVehicleType();" >
					<option value=""><?php echo $tr->translate("Vehicle Type");?></option>
					<option value="-1"><?php echo $tr->translate("Add New")?></option>
					<?php if(!empty($this->vehicle_type)){foreach ($this->vehicle_type as $rs){?>
					<option value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
					<?php }}?>
			  </select>
		   </div>
		</div>
		<div class="form-group">
		   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">
				<?php echo $tr->translate("Is Available");?>
		   </label>
		  <div class="col-md-7 col-sm-7 col-xs-7">
			  <select class="form-control select2" name="isAvailable" id="isAvailable" placeholder="" >
					<option value="1"><?php echo $tr->translate("Available");?></option>
					<option value="0"><?php echo $tr->translate("Not Available");?></option>
			  </select>
		   </div>
		</div>
		<div class="form-group">
		   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">
				<?php echo $tr->translate("Description");?>
		   </label>
		  <div class="col-md-7 col-sm-7 col-xs-7">
				<textarea class="form-control" rows="" cols="" name="note" id="note" placeholder="<?php echo $tr->translate("Description");?>"></textarea>
		   </div>
		</div>
	</div>
	
	
	
	<div class="col-xs-12">
		<div class="row">
			<div class="col-md-12">
				<table width="100%" id="table_row" border="1px" style="margin-top:5px; border-collapse: collapse; border:1px solid #ccc;width:100%;">
					<thead>
						<tr id="head-title" align="right" style="font-size:15px; height: 40px; border:1px solid #4c6184 !important;white-space: nowrap;">
							<th class="aligncenter">#</th>
							<th class="aligncenter"><?php echo $tr->translate("From Location");?></th>
							<th class="aligncenter"><?php echo $tr->translate("To Location");?></th>
							<th class="aligncenter"><?php echo $tr->translate("Duration");?></th>
							<th class="aligncenter"><?php echo $tr->translate("Cost Price");?></th>
							<th class="aligncenter"><?php echo $tr->translate("Sell Price");?></th>
							<th class="aligncenter"><?php echo $tr->translate("Discount");?>(%)</th>
							<th class="aligncenter"><?php echo $tr->translate("Delete");?></th>
						</tr>
					</thead>
					<tbody id="lbl_price">
					</tbody>
				</table>
			</div>
		</div>
	</div>
	
	<div class="col-xs-12">
		<div class="row">
			<div class="col-md-12">
				&nbsp;
			</div>
		</div>
	</div>
	
	<div class="col-xs-12">
		<div class="row">
			<div class="col-md-12">
				<input type="button" id="addrow" value="<?php echo $tr->translate('Add Price Row');?>" class="btn btn-primary black save" onclick="addRow();" />
				<input type="hidden" name="identity" id="identity" />
			</div>
		</div>
	</div>
	
	<div class="col-xs-12">
		<div class="row">
			<div class="col-md-12">
				&nbsp;
			</div>
		</div>
	</div>
	<div class="col-xs-12">
		<div class="row">
			<div class="col-md-12">
				&nbsp;
			</div>
		</div>
	</div>
	<div class="col-xs-12">
		<div class="row">
			<div class="col-md-12">
				<div class="text-center">
					<input id="submitButton" type="submit" value="<?php echo $tr->translate('SAVE');?>" class="btn btn-primary black save" />
				</div>
			</div>
		</div>
	</div>
	
</form>
<script type="text/javascript">

	$('#frm').submit(function() {
		supplyerId=$("#supplyerId").val();
		if(supplyerId==''){
			alert("Please select supplyer !!!");
			$('#supplyerId').focus;
			return false;	
		}

		vehicleType=$("#vehicleType").val();
		if(vehicleType==''){
			alert("Please select vehicle type !!!");
			$('#vehicleType').focus;
			return false;	
		}

		validate = checkValidateAddRow();
		if(validate==false){
			alert("Please validate Add Row !!! ");
			return false;
		}
		
		var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
		if (r == true) {
			$("#submitButton").attr("disabled", true);
			return true;
		} else {
		   return false;	    
		}
	});

	$( document ).ready(function() {
		addRow();
	});

	index=0;
	function addRow(){
		index++;
		template='<tr align="center" id="row_price_'+index+'">';
		template+='<td width="2%">'+index+'</td>';
		
		template+='<td width="20%"><select class="form-control select2" id="from_location_'+index+'" name="from_location_'+index+'" >';
		template+='<option value=""><?php echo $tr->translate("From Location");?></option>';
			<?php foreach($this->location as $location){?>
				template+='<option value="'+<?php echo $location['id']?>+'"><?php echo $location['name'];?></option>';
			<?php }?>
		template+='</select>';
		
		template+='<td width="20%"><select class="form-control select2" id="to_location_'+index+'" name="to_location_'+index+'" >';
		template+='<option value=""><?php echo $tr->translate("To Location");?></option>';
			<?php foreach($this->location as $location){?>
				template+='<option value="'+<?php echo $location['id']?>+'"><?php echo $location['name'];?></option>';
			<?php }?>
		template+='</select></td>';
		
		template+='<td><input style="text-align:center;" type="text" id="duration_'+index+'" name="duration_'+index+'"  value="" class="form-control"></td>';
		template+='<td><input style="text-align:center;" onkeypress="return isNumberKey(event);" type="text" id="cost_'+index+'" name="cost_'+index+'"  value="" class="form-control"></td>';
		template+='<td><input style="text-align:center;" onkeypress="return isNumberKey(event);" type="text" id="price_'+index+'" name="price_'+index+'"  value="" class="form-control"></td>';
		template+='<td><input style="text-align:center;" onkeypress="return isNumberKey(event);" onkeyup="checkAmount('+index+');" type="text" id="discount_'+index+'" name="discount_'+index+'"  value="" class="form-control"></td>';
		template+='<td><button style="background: #ff3b3b;color: #fff;" type="button" onClick="deleteRecord('+index+')" name="deleteSale" class="btn default red"><?php echo $tr->translate("Delete");?></button></td>';
		
		template+='</tr>';
		$('#lbl_price').append(template);
		if($('#identity').val()!="") {
			var identity = $('#identity').val();
			$('#identity').val(identity+','+index);
		} else {$('#identity').val(index);}
		
		$("#from_location_"+index).select2();
		$("#to_location_"+index).select2();
	}
	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		$("#row_price_"+index).remove();
	}

	function checkAmount(index){
		discount = $('#discount_'+index).val();
		if(discount>100){
			alert("Can not discount more than 100% !!! ");
			$('#discount_'+index).val(100);
		}
	}

	function checkValidateAddRow(){
		var rowId = $('#identity').val();
		if(rowId!=''){
			var rowIDArray = rowId.split(',');
			for(var n = 0; n < rowIDArray.length; n++) {
				from_location = $('#from_location_'+rowIDArray[n]).val();
				to_location = $('#to_location_'+rowIDArray[n]).val();
				cost = parseFloat($('#cost_'+rowIDArray[n]).val());
				cost = isNaN(cost)?0:cost;
				price = parseFloat($('#price_'+rowIDArray[n]).val());
				price = isNaN(price)?0:price;
				//alert(cost+" , "+price);
				if((to_location=='' || from_location=='' || cost=='' || price=='' || cost==0 || price==0) || (to_location==from_location) || (cost>price) ){
					return false;
				}
			}
		}else{
			return false;
		}
		return true;
	}
	
	function isNumberKey(evt)
	{
	  	var charCode = (evt.which) ? evt.which : event.keyCode;
	  	if (charCode != 46 && charCode != 45 && charCode > 31 && (charCode < 48 || charCode > 57)){
			return false;
	  	}else{
			return true;
	  	}
	}
	
	function getPopupSupplyer(){
		val = $('#supplyerId').val();
		if(val==-1){
			$('#supplyerpopup').modal('show');
		}
	}
	
	<?php $url_add_customer =  $this->url(array('module'=>'vehicle','controller'=>'index','action'=>'add-supplyerpopup')); ?>
	function addNewSupplyer(){
		supplyerName = $("#supplyerName").val();
		if(supplyerName==''){
			$("#supplyerName").focus();
			return false;
		} 
		tel = $("#tel").val();
		if(tel==''){
			$("#tel").focus();
			return false;
		} 
		email = $("#email").val();
		if(email==''){
			$("#email").focus();
			return false;
		} 
		$('#saveSupplyer').attr("disabled", true);
		$.ajax({
			url: "<?php echo $url_add_customer;?>",
			type: "post",
			data: $('#frmsupplyer').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				//alert(rs);
				$('#supplyerId').append($("<option></option>").attr("value",rs).attr("selected",true).text(supplyerName));                       
				$("#supplyerId").select2();
				
				$('#supplyerpopup').modal('hide');
				$('#saveSupplyer').attr("disabled", false);
			},
			error:function(err){
				alert("faile insert");
			}
		});
	}
	
	function getPopupVehicleType(){
		val = $('#vehicleType').val();
		if(val==-1){
			$('#vehicletypepopup').modal('show');
		}
	}
	
	<?php $url_add_customer =  $this->url(array('module'=>'vehicle','controller'=>'index','action'=>'add-vehicletypepopup')); ?>
	function addNewVehicleType(){
		title = $("#title").val();
		if(title==''){
			$("#title").focus();
			return false;
		} 
		amountSeat = $("#amountSeat").val();
		if(amountSeat==''){
			$("#amountSeat").focus();
			return false;
		} 
		serviceType = $("#serviceType").val();
		if(serviceType==-1){
			alert("Please select service type !!! ");
			return false;
		} 
		$('#saveVehicleType').attr("disabled", true);
		$.ajax({
			url: "<?php echo $url_add_customer;?>",
			type: "post",
			data: $('#frmvehicletype').serialize(),
			success: function(data){
				rs = $.parseJSON(data);
				//alert(rs);
				$('#vehicleType').append($("<option></option>").attr("value",rs).attr("selected",true).text(title));                       
				$("#vehicleType").select2();
				
				$('#vehicletypepopup').modal('hide');
				$('#saveVehicleType').attr("disabled", false);
			},
			error:function(err){
				alert("faile insert");
			}
		});
	}
</script>

<div id="supplyerpopup" class="modal fade" tabindex="-1" data-width="1000">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="portlet-title">
				<div class="col-sm-12 border-botom">
					<div class="col-sm-12">
						<h4 class="m-t-0" style="text-align:center;"><?php echo $tr->translate("Add Supplier");?></h4>
					</div>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmsupplyer" name="frmsupplyer" dojoType="dijit.form.Form" autoComplete="off" enctype="application/x-www-form-urlencoded" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-3">
								<?php echo $tr->translate("Supplier Name");?>
							</label>
							<div class="col-md-9">
								<div class="input-icon right">
									<input name="supplyerName" id="supplyerName" class="form-control" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">
								<?php echo $tr->translate("Phone");?>
							</label>
							<div class="col-md-9">
								<div class="input-icon right">
									<input name="tel" id="tel" class="form-control" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">
								<?php echo $tr->translate("Email");?>
							</label>
							<div class="col-md-9">
								<div class="input-icon right">
									<input type="email" name="email" id="email" class="form-control" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label  class="col-md-12 " style="text-align:center;">
								<button type="button" id="saveSupplyer" name="save_receiver" onclick="addNewSupplyer();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("រក្សាទុក")?> </button>
							</label>
						</div>
					</div>
				</form>
			</div>
        </div>
    </div>
 </div>
 
 
 <div id="vehicletypepopup" class="modal fade" tabindex="-1" data-width="1000">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="portlet-title">
				<div class="col-sm-12 border-botom">
					<div class="col-sm-12">
						<h4 class="m-t-0" style="text-align:center;"><?php echo $tr->translate("Add Vehicle Type");?></h4>
					</div>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frmvehicletype" name="frmvehicletype" dojoType="dijit.form.Form" autoComplete="off" enctype="application/x-www-form-urlencoded" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-4">
								<?php echo $tr->translate("Vehicle Type Name");?>
							</label>
							<div class="col-md-8">
								<div class="input-icon right">
									<input name="title" id="title" class="form-control" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-4">
								<?php echo $tr->translate("Service Type");?>
							</label>
							<div class="col-md-8">
								<div class="input-icon right">
									<select name="serviceType" id="serviceType" class="form-control " >
										<option value="-1">Select Service</option>
										<option value="1">Taxi</option>
										<option value="2">Ferries</option>
									</select>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-4">
								<?php echo $tr->translate("Amount Seat");?>
							</label>
							<div class="col-md-8">
								<div class="input-icon right">
									<input name="amountSeat" id="amountSeat" class="form-control" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-4">
								<?php echo $tr->translate("Amount Big Luggage");?>
							</label>
							<div class="col-md-8">
								<div class="input-icon right">
									<input name="amountCase" id="amountCase" class="form-control" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-4">
								<?php echo $tr->translate("Amount Small Luggage");?>
							</label>
							<div class="col-md-8">
								<div class="input-icon right">
									<input name="amountSmallCase" id="amountSmallCase" class="form-control" />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label  class="col-md-12 " style="text-align:center;">
								<button type="button" id="saveVehicleType" name="save_receiver" onclick="addNewVehicleType();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("រក្សាទុក")?> </button>
							</label>
						</div>
					</div>
				</form>
			</div>
        </div>
    </div>
 </div>