<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('កែប្រែកំណត់តម្លៃរថយន្ត'));
echo $this->headTitle();
?>
<style>
.form-group {
    margin-bottom: 5px;
}
.form-horizontal .control-label {
    text-align: left;
}
.thumb-xl {
    height: 180px;
    width: 150px;
}
div.browe_photo .input-group {
    display: block;
}
label#error {
    color: #F44336;
}

.aligncenter{
	text-align: center;
	background:#ecba11;
	color:#584509;
}

</style>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<form id="frm" class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" autocomplete="off">
	    		<div class="col-sm-12 border-botom">
	    			<div class="col-sm-8">
	    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;កែប្រែកំណត់តម្លៃរថយន្ត</h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
				<div class="col-xs-2"></div>
				<div class="col-xs-8">
					<div class="form-group">
						<label id="error" class="col-md-12 col-sm-12 col-xs-12 text-center" ></label>
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">ឈ្មោះអ្នកផ្គត់ផ្គង់
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                    	<select class="form-control select2me" name="supplyerId" id="supplyerId" placeholder="ប្រភេទរថយន្ត" >
	                      		<option value="">ជ្រើសរើសអ្នកផ្គត់ផ្គង់</option>
	                      		<?php if(!empty($this->supplyer)){foreach ($this->supplyer as $rs){?>
								<option value="<?php echo $rs['id']?>" <?php if($rs['id']==$this->row['supplyerId']){echo "selected='selected'";}?>><?php echo $rs['name']?></option>
								<?php }}?>
						    </select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">ប្រភេទរថយន្ត </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                      <select class="form-control select2me" name="vehicleType" id="vehicleType" placeholder="ប្រភេទរថយន្ត" >
	                      		<option value="">ជ្រើសរើសប្រភេទរថយន្ត</option>
	                      		<?php if(!empty($this->vehicle_type)){foreach ($this->vehicle_type as $rs){?>
								<option value="<?php echo $rs['id']?>" <?php if($rs['id']==$this->row['vehicleType']){echo "selected='selected'";}?>><?php echo $rs['name']?></option>
								<?php }}?>
						  </select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">ទំនេរ(is available) </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                      <select class="form-control select2me" name="isAvailable" id="isAvailable" placeholder="" >
								<option value="1" <?php if($this->row['isAvailable']==1){echo "selected='selected'";}?>>ទំនេរ</option>
								<option value="0" <?php if($this->row['isAvailable']==0){echo "selected='selected'";}?>>មិនទំនេរ</option>
						  </select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">ពណ៍នា </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                  		<textarea class="form-control" rows="" cols="" name="note" id="note" placeholder="ពណ៍នា"><?php echo $this->row['note']?></textarea>
	                   </div>
	                </div>
				</div>
				
				
				<div class="col-xs-12">
					<div class="row">
						<div class="col-md-12">
							<table width="100%" id="table_row" border="1px" style="margin-top:5px; border-collapse: collapse; border:1px solid #ccc;width:100%;">
								<thead>
									<tr id="head-title" align="right" style="font-size:15px; height: 40px; border:1px solid #4c6184 !important;white-space: nowrap;">
										<th class="aligncenter">#</th>
										<th class="aligncenter">ពីទីតាំង</th>
										<th class="aligncenter">ទៅទីតាំង</th>
										<th class="aligncenter">រយៈពេលធ្វើដំណើរ</th>
										<th class="aligncenter">តម្លៃទិញចូល</th>
										<th class="aligncenter">តម្លៃជួល</th>
										<th class="aligncenter">បញ្ចុះតម្លៃ(%)</th>
										<th class="aligncenter">លុប</th>
									</tr>
								</thead>
								<tbody id="lbl_price">
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<div class="col-xs-12">
					<div class="row">
						<div class="col-md-12">
							&nbsp;
						</div>
					</div>
				</div>
				
				<div class="col-xs-12">
					<div class="row">
						<div class="col-md-12">
							<input type="button" id="addrow" value="<?php echo $tr->translate('បន្ថែមតម្លៃជួល');?>" class="btn btn-primary black save" onclick="addRow();" />
							<input type="hidden" name="identity" id="identity" />
						</div>
					</div>
				</div>
				
				<div class="col-xs-12">
					<div class="row">
						<div class="col-md-12">
							&nbsp;
						</div>
					</div>
				</div>
				<div class="col-xs-12">
					<div class="row">
						<div class="col-md-12">
							<div class="text-center">
								<input id="backbutton" class="btn btn-primary block" type="button" onclick="window.location = '<?php echo $this->url(array('module'=>'vehicle','controller'=>"index",'action'=>'index'),null,true); ?>';" value="<?php echo $tr->translate('GO_BACK');?>" />
								<input type="submit" value="<?php echo $tr->translate('GO_EDIT');?>" class="btn btn-primary black save" />
							</div>
						</div>
					</div>
				</div>
				
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">

	$('#frm').submit(function() {
		supplyerId=$("#supplyerId").val();
		if(supplyerId==''){
			alert("Please select supplyer !!!");
			$('#supplyerId').focus;
			return false;	
		}
	
		vehicleType=$("#vehicleType").val();
		if(vehicleType==''){
			alert("Please select vehicle type !!!");
			$('#vehicleType').focus;
			return false;	
		}
	
		validate = checkValidateAddRow();
		if(validate==false){
			alert("Please validate Add Row !!! ");
			return false;
		}
		
		var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
		if (r == true) {
			$("#submitButton").attr("disabled", true);
			return true;
		} else {
		   return false;	    
		}
	});

	$( document ).ready(function() {
		Initailize();
	});
	index=0;
	function Initailize(){
		
		<?php if(!empty($this->row_detail)){foreach ($this->row_detail as $rs){?>
		
		index++;
		template='<tr align="center" id="row_price_'+index+'">';
		template+='<td width="2%">'+index+'</td>';
		
		template+='<td width="20%"><select class="form-control select2me" id="from_location_'+index+'" name="from_location_'+index+'" >';
		template+='<option value="">from location</option>';
			<?php foreach($this->location as $location){?>
				template+='<option value="'+<?php echo $location['id']?>+'"><?php echo $location['name'];?></option>';
			<?php }?>
		template+='</select></td>';
		
		template+='<td width="20%"><select class="form-control select2me" id="to_location_'+index+'" name="to_location_'+index+'" >';
		template+='<option value="">to location</option>';
			<?php foreach($this->location as $location){?>
				template+='<option value="'+<?php echo $location['id']?>+'"><?php echo $location['name'];?></option>';
			<?php }?>
		template+='</select></td>';
		
		template+='<td><input style="text-align:center;" type="text" id="duration_'+index+'" name="duration_'+index+'"  value="" class="form-control"></td>';
		template+='<td><input style="text-align:center;" type="text" id="cost_'+index+'" name="cost_'+index+'"  value="" class="form-control"></td>';
		template+='<td><input style="text-align:center;" type="text" id="price_'+index+'" name="price_'+index+'"  value="" class="form-control"></td>';
		template+='<td><input style="text-align:center;" type="text" id="discount_'+index+'" name="discount_'+index+'"  value="" class="form-control"></td>';
		template+='<td><button style="background: #ff3b3b;color: #fff;" type="button" onClick="deleteRecord('+index+')" name="deleteSale" class="btn default red">លុប</button></td>';
		
		template+='</tr>';
		$('#lbl_price').append(template);
		if($('#identity').val()!="") {
			var identity = $('#identity').val();
			$('#identity').val(identity+','+index);
		} else {$('#identity').val(index);}
		
		$("#from_location_"+index).select2();
		$("#to_location_"+index).select2();
		
		$('#from_location_'+index).val(<?php echo $rs['from_location'];?>).select2();
		$('#to_location_'+index).val(<?php echo $rs['to_location'];?>).select2();
		$('#duration_'+index).val("<?php echo $rs['duration'];?>");
		$('#cost_'+index).val(<?php echo $rs['cost'];?>);
		$('#price_'+index).val(<?php echo $rs['price'];?>);
		$('#discount_'+index).val(<?php echo $rs['discount'];?>);
		<?php }}?>
	}

	
	function addRow(){
		index++;
		template='<tr align="center" id="row_price_'+index+'">';
		template+='<td width="2%">'+index+'</td>';
		
		template+='<td width="20%"><select class="form-control select2me" id="from_location_'+index+'" name="from_location_'+index+'" >';
		template+='<option value="">from location</option>';
			<?php foreach($this->location as $location){?>
				template+='<option value="'+<?php echo $location['id']?>+'"><?php echo $location['name'];?></option>';
			<?php }?>
		template+='</select></td>';
		
		template+='<td width="20%"><select class="form-control select2me" id="to_location_'+index+'" name="to_location_'+index+'" >';
		template+='<option value="">to location</option>';
			<?php foreach($this->location as $location){?>
				template+='<option value="'+<?php echo $location['id']?>+'"><?php echo $location['name'];?></option>';
			<?php }?>
		template+='</select></td>';
		
		template+='<td><input style="text-align:center;" type="text" id="duration_'+index+'" name="duration_'+index+'"  value="" class="form-control"></td>';
		template+='<td><input style="text-align:center;" type="text" id="cost_'+index+'" name="cost_'+index+'"  value="" class="form-control"></td>';
		template+='<td><input style="text-align:center;" type="text" id="price_'+index+'" name="price_'+index+'"  value="" class="form-control"></td>';
		template+='<td><input style="text-align:center;" type="text" id="discount_'+index+'" name="discount_'+index+'"  value="" class="form-control"></td>';
		template+='<td><button style="background: #ff3b3b;color: #fff;" type="button" onClick="deleteRecord('+index+')" name="deleteSale" class="btn default red">លុប</button></td>';
		
		template+='</tr>';
		$('#lbl_price').append(template);
		if($('#identity').val()!="") {
			var identity = $('#identity').val();
			$('#identity').val(identity+','+index);
		} else {$('#identity').val(index);}
		
		$("#from_location_"+index).select2();
		$("#to_location_"+index).select2();
	}

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		$("#row_price_"+index).remove();
	}

	function checkAmount(index){
		discount = $('#discount_'+index).val();
		if(discount>100){
			alert("Can not discount more than 100% !!! ");
			$('#discount_'+index).val(100);
		}
	}

	function checkValidateAddRow(){
		var rowId = $('#identity').val();
		if(rowId!=''){
			var rowIDArray = rowId.split(',');
			for(var n = 0; n < rowIDArray.length; n++) {
				from_location = $('#from_location_'+rowIDArray[n]).val();
				to_location = $('#to_location_'+rowIDArray[n]).val();
				cost = parseFloat($('#cost_'+rowIDArray[n]).val());
				cost = isNaN(cost)?0:cost;
				price = parseFloat($('#price_'+rowIDArray[n]).val());
				price = isNaN(price)?0:price;
				//alert(cost+" , "+price);
				if((to_location=='' || from_location=='' || cost=='' || price=='' || cost==0 || price==0) || (to_location==from_location) || (cost>price) ){
					return false;
				}
			}
		}else{
			return false;
		}
		return true;
	}
	
	function isNumberKey(evt)
	{
	  	var charCode = (evt.which) ? evt.which : event.keyCode;
	  	if (charCode != 46 && charCode != 45 && charCode > 31 && (charCode < 48 || charCode > 57)){
			return false;
	  	}else{
			return true;
	  	}
	}

	
</script>