<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('Edit Position'));
echo $this->headTitle();
$position = $this->position;

?>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-star"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Edit Position")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    				<div class="buttun-block">
    					<?php if ($position['status']==0){?>
						<a class="btn btn-primary unblock" href="<?php echo $this->baseUrl()."/employee/position/update?blocked=1&id=".$position['id'];?>"><?php echo $tr->translate("ACTIVE")?></a>
						<?php }else if ($position['status']==1){?>
						<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/employee/position/update?blocked=0&id=".$position['id']?>"><?php echo $tr->translate("DEACTIVE")?></a>
						<?php }?>
					</div>
    			</div>
    		</div>
    		
			<div class="col-sm-8">
				<form  class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
					<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('Position Title')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	<input class="form-control"  type="text" required="true" name="title" id="title" placeholder="<?php echo $tr->translate('Position Title')?>" value="<?php echo $position['title'];?>"/>
	                   		<input class="form-control"  type="hidden"  name="id" id="id"  value="<?php echo $position['id'];?>"/>
	                   </div>
	                </div>
	               <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('DESCRIPTION')?> :
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                   		<textarea class="form-control" rows="5" id="description" name="description"><?php echo $position['description'];?></textarea>
	                   </div>
	                </div>
                    <div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-center">
								<input class="btn btn-primary black save" type="submit" value="<?php echo $tr->translate('SAVE');?>" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" /> 
			                </div>
	                    </div>
                    </div>
	               
	              </form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });
</script>