<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<title>About Us</title>
<div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<form  class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
    			
    			<div class="col-sm-12 border-botom">
	    			<div class="col-sm-8">
	    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("About Us")?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    				<a class="btn btn-primary black save" href="<?php echo $this->baseUrl()."/setting/aboutus/add";?>"><?php echo $tr->translate("ADD_NEW")?></a>
	    			</div>
	    		</div>
	    		<div class="col-sm-12" style="white-space: nowrap;">
					<?php echo $this->list;?>
				</div>
			</form>
		</div>
	</div>
</div>

