<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<title><?php echo $tr->translate("USERACCESS")?></title>
 <!-- START PAGE CONTENT -->
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-user"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("USERACCESS")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
			<div class="col-sm-12">
				<div class="card-box">
					<?php $url = Application_Form_FrmMessage::getUrl("/rsvacl/useraccess/view-user-access?id=");?>
					<?php echo $this->list;?>
				</div>
			</div>
