<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('Add Customer'));
echo $this->headTitle();
?>
<style>
.form-group {
    margin-bottom: 5px;
}
.form-horizontal .control-label {
    text-align: left;
}
.thumb-xl {
    height: 180px;
    width: 150px;
}
div.browe_photo .input-group {
    display: block;
}
label#error {
    color: #F44336;
}

</style>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<form  class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	    		<div class="col-sm-12 border-botom">
	    			<div class="col-sm-8">
	    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Add Customer")?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
    		
				<div class="col-sm-8">
					<div class="form-group">
						<label id="error" class="col-md-12 col-sm-12 col-xs-12 text-center" ></label>
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">
	                   		<?php echo $tr->translate('ឈ្មោះអតិថិជន')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                    	<input class="form-control" type="text"  name="customerName" id="customerName" placeholder="<?php echo $tr->translate('ឈ្មោះអតិថិជន')?>"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('ភេទ')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                      <select class="form-control select2me" name="gender" id="gender" placeholder="<?php echo $tr->translate('ភេទ')?>" >
								<option value="1">ប្រុស</option>
								<option value="2">ស្រី</option>
	                      </select>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('អាយុ')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="age" id="age" placeholder="<?php echo $tr->translate('អាយុ');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('លេខទូរសព្ទ')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="tel" id="tel" placeholder="<?php echo $tr->translate('លេខទូរសព្ទ');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('អ៊ីមែល')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="email" id="email" placeholder="<?php echo $tr->translate('អ៊ីមែល');?>" />
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Password')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="password" id="password" placeholder="<?php echo $tr->translate('Password');?>" />
	                   </div>
	                </div>
	                
	               <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Is Verify')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                      <select class="form-control select2me" name="isVerify" id="isVerify" placeholder="<?php echo $tr->translate('Is Verify')?>" >
								<option value="1">true</option>
								<option value="0">false</option>
	                      </select>
	                   </div>
	                </div>
	                
	                
	                
				</div>
				<div class="col-sm-4">
					<div class="form-group">
						<div class="col-md-12 col-sm-12 col-xs-12 text-center">
	                    	<div class="thumb-xl member-thumb m-b-10 center-block">
	                            <img id="profile-img-tag" src="<?php echo $this->baseUrl()."/images/profile.jpg";?>" class=" img-thumbnail" alt="profile-image" style="height: 100%;width: 100%;">
		                    </div>
	                    </div>
	             	</div>
                	<div class="form-group">
	                     <div class="col-md-12 col-sm-12 col-xs-12 m-t-10 text-center browe_photo">
	                     	<input type="file" id="profile-img" class="filestyle" data-input="false" name="photo" data-buttontext="<?php echo $tr->translate('រូបភាព')?>">
	                  	 </div>
                 	</div>
				</div>
				<div class="col-sm-12">
                	<div class="form-group">
	                    &nbsp;
                    </div>
				</div>
				<div class="col-sm-12">
                	<div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-center">
								<input id="btnsubmit" class="btn btn-primary black save" type="submit" value="<?php echo $tr->translate('SAVE');?>" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" /> 
			                </div>
	                    </div>
                    </div>
				</div>
				
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57)) {
            var msg='You can input only number.';
    		alert(msg);
    		return false;
        }
        return true;
    }

</script>