<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("ផ្លាស់ប្ដូរពាក្យសម្ងាត់")); 
	echo $this->headTitle();
?>   
<style>
.form-group {
    margin-bottom: 5px;
}
.form-horizontal .control-label {
    text-align: left;
}
.thumb-xl {
    height: 180px;
    width: 150px;
}
div.browe_photo .input-group {
    display: block;
}
label#error {
    color: #F44336;
}

</style>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<form id="frm" class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" autocomplete="off">
	    		<div class="col-sm-12 border-botom">
	    			<div class="col-sm-8">
	    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("ផ្លាស់ប្ដូរពាក្យសម្ងាត់")?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    				<div class="buttun-block">
						</div>
	    			</div>
	    		</div>
	    		<div class="form-group">
					<div class="col-sm-12">
						&nbsp;
					</div>
				</div>
	    		<div class="form-group">
					<div class="col-sm-12">
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
						<label class="col-md-2 col-sm-2 col-xs-2 control-label">
							លេខសម្ងាត់ បច្ចុប្បន្ន 
						</label>
						<div class="col-md-4 col-sm-4 col-xs-4">
							<input type="password" name="oldPassword" id="oldPassword" class="form-control" />
		    			</div>
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
					</div>
				</div>
				<br>
				<div class="form-group">
					<div class="col-sm-12">
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
						<label class="col-md-2 col-sm-2 col-xs-2 control-label">
							លេខសម្ងាត់ ថ្មី 
						</label>
						<div class="col-md-4 col-sm-4 col-xs-4">
							<input type="password" name="newPassword" id="newPassword" class="form-control" />
		    			</div>
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
					</div>
				</div>
				<br>
				<div class="form-group">
					<div class="col-sm-12">
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
						<label class="col-md-2 col-sm-2 col-xs-2 control-label">
							បញ្ជាក់ លេខសម្ងាត់ ថ្មី 
						</label>
						<div class="col-md-4 col-sm-4 col-xs-4">
							<input type="password" name="reNewPassword" id="reNewPassword" class="form-control" />
		    			</div>
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
					</div>
				</div>
				<br><br><br><br><br>
				<div class="form-group">
					<div class="col-sm-12">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-center">
	                    	 	<input id="backbutton" class="btn btn-primary block" type="button" onclick="window.location = '<?php echo $this->url(array('module'=>'booking','controller'=>"customer",'action'=>'index'),null,true); ?>';" value="<?php echo $tr->translate('ត្រលប់ក្រោយ');?>" />
								<input id="btnsubmit" class="btn btn-primary black save" type="submit" value="<?php echo $tr->translate('រក្សាទុក');?>" /> 
			                </div>
	                    </div>
                    </div>
				</div>
			</form>
		</div>
	</div>
</div>
<!-- END PAGE CONTENT -->
<!-- Modal -->
<script>
$("form").submit(function(){
	if($("#oldPassword").val()==''){
		$("#oldPassword").focus();
		return false;
	}
	if($("#newPassword").val()==''){
		$("#newPassword").focus();
		return false;
	}
	if($("#reNewPassword").val()==''){
		$("#reNewPassword").focus();
		return false;
	}
	
	if($("#newPassword").val() != $("#reNewPassword").val() ){
		alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
		$("#newPassword").val('');
		$("#reNewPassword").val('');
		$("#newPassword").focus();
		return false;
	}				
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
		$("#btnsubmit").attr("disabled", true);
		return true;
	} else {
	   return false;	    
	}
	//return true;
});
</script>