<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("Change Password")); 
	echo $this->headTitle();
?>   
<style>
.form-group {
    margin-bottom: 5px;
}
.form-horizontal .control-label {
    text-align: left;
}
.thumb-xl {
    height: 180px;
    width: 150px;
}
div.browe_photo .input-group {
    display: block;
}
label#error {
    color: #F44336;
}

</style>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<form id="frm" class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	    		
	    		<div class="col-sm-12 border-botom">
	    			<div class="col-sm-8">
	    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Change Password")?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    				<div class="buttun-block">
						</div>
	    			</div>
	    		</div>
	    		<div class="form-group">
					<div class="col-sm-12">
						&nbsp;
					</div>
				</div>
	    		<div class="form-group">
					<div class="col-sm-12">
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
						<label class="col-md-2 col-sm-2 col-xs-2 control-label">
							Password បច្ចុប្បន្ន 
						</label>
						<div class="col-md-4 col-sm-4 col-xs-4">
							<input type="password" name="oldPassword" id="oldPassword" class="form-control" />
		    			</div>
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
					</div>
				</div>
				<br>
				<div class="form-group">
					<div class="col-sm-12">
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
						<label class="col-md-2 col-sm-2 col-xs-2 control-label">
							Password ថ្មី 
						</label>
						<div class="col-md-4 col-sm-4 col-xs-4">
							<input type="password" name="newPassword" id="newPassword" class="form-control" />
		    			</div>
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
					</div>
				</div>
				<br>
				<div class="form-group">
					<div class="col-sm-12">
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
						<label class="col-md-2 col-sm-2 col-xs-2 control-label">
							បញ្ជាក់ Password ថ្មី 
						</label>
						<div class="col-md-4 col-sm-4 col-xs-4">
							<input type="password" name="reNewPassword" id="reNewPassword" class="form-control" />
		    			</div>
						<div class="col-md-3 col-sm-3 col-xs-3">
		    			</div>
					</div>
				</div>
				<br><br><br><br><br>
				<div class="form-group">
					<div class="col-sm-12">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-center">
								<input id="btnsubmit" class="btn btn-primary black save" type="submit" value="<?php echo $tr->translate('SAVE');?>" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" /> 
			                </div>
	                    </div>
                    </div>
				</div>
			</form>
		</div>
	</div>
</div>
<!-- END PAGE CONTENT -->
<!-- Modal -->
<script>
$("form").submit(function(){
	if($("#newPassword").val() != $("#reNewPassword").val() ){
		alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
		$("#newPassword").val('');
		$("#reNewPassword").val('');
		return false;
	}				
	return true;
});
</script>