<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('កែប្រែអតិថិជន'));
	echo $this->headTitle();

	$photo = $this->baseUrl()."/images/profile.jpg";
	$customer = $this->customer;
	$file="";
	if (!empty($customer['photo'])){
		$photo = $this->baseUrl()."/images/all/customer/".$customer['photo'];
		$file= $customer['photo'];
	}
?>
<style>
.form-group {
    margin-bottom: 5px;
}
.form-horizontal .control-label {
    text-align: left;
}
.thumb-xl {
    height: 180px;
    width: 150px;
}
div.browe_photo .input-group {
    display: block;
}
label#error {
    color: #F44336;
}
.card-employee {
    border: solid 1px #cecccc;
    border-radius: 5px;
    width: 14cm;
    padding: 10px;
        color: #0670c3;
}
</style>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<form id="frm" class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" autocomplete="off">
	    		<div class="col-sm-12 border-botom">
	    			<div class="col-sm-8">
	    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("កែប្រែអតិថិជន");?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
    		
				<div class="col-sm-8">
					<div class="form-group">
						<label id="error" class="col-md-12 col-sm-12 col-xs-12 text-center" ></label>
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name">
	                   		<?php echo $tr->translate('ឈ្មោះអតិថិជន')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                    	<input class="form-control" type="text" name="customerName" id="customerName" value="<?php echo $customer['customerName']?>" placeholder="<?php echo $tr->translate('ឈ្មោះអតិថិជន')?>"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('ភេទ')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
						  <select class="form-control select2me" name="gender" id="gender" placeholder="<?php echo $tr->translate('ភេទ')?>" >
								<option value="1" <?php if($customer['gender']==1){echo "selected='selected'";}?>>ប្រុស</option>
								<option value="2" <?php if($customer['gender']==2){echo "selected='selected'";}?>>ស្រី</option>
	                      </select>
					  </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('អាយុ')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="age" id="age" value="<?php echo $customer['age']?>" placeholder="<?php echo $tr->translate('អាយុ');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('លេខទូរសព្ទ')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="tel" id="tel" value="<?php echo $customer['tel']?>" placeholder="<?php echo $tr->translate('លេខទូរសព្ទ');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('អ៊ីមែល')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="email" class="form-control"   name="email" id="email" value="<?php echo $customer['email']?>" placeholder="<?php echo $tr->translate('អ៊ីមែល');?>" />
	                   </div>
	                </div>
	                
	               <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Is Verify')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                      <select class="form-control select2me" name="isVerify" id="isVerify" placeholder="<?php echo $tr->translate('Is Verify')?>" >
								<option value="1" <?php if($customer['isVerify']==1){echo "selected='selected'";}?>>Verified</option>
								<option value="0" <?php if($customer['isVerify']==0){echo "selected='selected'";}?>>Not Verified</option>
	                      </select>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('ស្ថានភាព')?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-7">
						  <select class="form-control select2me" name="status" id="status" placeholder="<?php echo $tr->translate('ស្ថានភាព')?>" >
								<option value="1" <?php if($customer['status']==1){echo "selected='selected'";}?>>ប្រើប្រាស់</option>
								<option value="0" <?php if($customer['status']==0){echo "selected='selected'";}?>>មិនប្រើប្រាស់</option>
	                      </select>
					   </div>
	                </div>
	                
				</div>
				<div class="col-sm-4">
					<div class="form-group">
						<div class="col-md-12 col-sm-12 col-xs-12 text-center">
	                    	<div class="thumb-xl member-thumb m-b-10 center-block">
	                            <img id="profile-img-tag" src="<?php echo $photo;?>" class=" img-thumbnail" alt="profile-image" >
		                        </div>
	                        </div>
	                 </div>
	                 <div class="form-group">
	                       <div class="col-md-12 col-sm-12 col-xs-12 m-t-10 text-center browe_photo">
	                        <input type="file" id="profile-img" class="filestyle" data-input="false" name="photo" data-buttontext="<?php echo $tr->translate('រូបភាព')?>">
	                  	  </div>
					 </div>
					 
					 
					 <div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-center">
	                    	 	<input type="hidden" name="oldLogo" id="oldLogo" class="form-control" value="<?php echo $customer['photo']?>" />
			                </div>
	                    </div>
                    </div>
				</div>
				
				<div class="col-sm-12">
                	<div class="form-group">
	                    &nbsp;
                    </div>
				</div>
				
				<div class="col-sm-12">
                	<div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-center">
	                    	 	<input id="backbutton" class="btn btn-primary block" type="button" onclick="window.location = '<?php echo $this->url(array('module'=>'booking','controller'=>"customer",'action'=>'index'),null,true); ?>';" value="<?php echo $tr->translate('ត្រលប់ក្រោយ');?>" />
								<input id="btnsubmit" class="btn btn-primary black save" type="submit" value="<?php echo $tr->translate('កែប្រែទិន្នន័យ');?>" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" /> 
			                </div>
	                    </div>
                    </div>
				</div>
				
			</form>
		</div>
	</div>
</div>
<?php // benchmark
    //QRtools::timeBenchmark();    
?>
<script type="text/javascript">

	$('#frm').submit(function() {
		customerName=$("#customerName").val();
		if(customerName==''){
			$('#customerName').focus();
			return false;	
		}
		tel=$("#tel").val();
		if(tel==""){
			$('#tel').focus();
			return false;	
		}
		email=$("#email").val();
		if(email==""){
			$('#email').focus();
			return false;	
		}
		var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
		if (r == true) {
			$("#btnsubmit").attr("disabled", true);
			return true;
		} else {
		   return false;	    
		}
	});

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57)) {
            var msg='You can input only number.';
    		alert(msg);
    		return false;
        }
        return true;
    }

</script>