<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('Add Employee'));
echo $this->headTitle();
?>
<style>
.form-group {
    margin-bottom: 5px;
}
.form-horizontal .control-label {
    text-align: left;
}
.thumb-xl {
    height: 180px;
    width: 150px;
}
div.browe_photo .input-group {
    display: block;
}
label#error {
    color: #F44336;
}

</style>
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<form  class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	    		<div class="col-sm-12 border-botom">
	    			<div class="col-sm-8">
	    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("Add Employee")?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
    		
			<div class="col-sm-8">
					<div class="form-group">
						<label id="error" class="col-md-12 col-sm-12 col-xs-12 text-center" ></label>
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Employee ID')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                    	<input class="form-control" onKeyup="CheckEmployeeCode();" type="text"  name="employeeCode" id="employeeCode" placeholder="<?php echo $tr->translate('Employee ID')?>"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Sure Name')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                      <input class="form-control" type="text"  name="sureName" id="sureName" placeholder="<?php echo $tr->translate('Sure Name')?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('First Name')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="firstName" id="firstName" placeholder="<?php echo $tr->translate('First Name');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Latin Name')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="latinName" id="latinName" placeholder="<?php echo $tr->translate('Latin Name');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Gender')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="gender" id="gender" placeholder="<?php echo $tr->translate('Gender');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('DOB')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="dob" id="dob" placeholder="<?php echo $tr->translate('DOB');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('POB')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="pob" id="pob" placeholder="<?php echo $tr->translate('POB');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Nation')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="nation" id="nation" placeholder="<?php echo $tr->translate('Nation');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Nationality')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="nationality" id="nationality" placeholder="<?php echo $tr->translate('Nationality');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Family Status')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="familyStatus" id="familyStatus" placeholder="<?php echo $tr->translate('Family Status');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('ID Card Number')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="idCardNumber" id="idCardNumber" placeholder="<?php echo $tr->translate('ID Card Number');?>" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Start Work Date')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="startWorkDate" id="startWorkDate" placeholder="<?php echo $tr->translate('Start Work Date');?>" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Framework')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="framework" id="framework" placeholder="<?php echo $tr->translate('Framework');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('POSITION')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="position" id="position" placeholder="<?php echo $tr->translate('POSITION');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Appointment Letter')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="appointmentLetter" id="appointmentLetter" placeholder="<?php echo $tr->translate('Appointment Letter');?>" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Organization')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"  name="organization" id="organization" placeholder="<?php echo $tr->translate('Organization');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Ministry')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"  name="ministry" id="ministry" placeholder="<?php echo $tr->translate('Ministry');?>" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Education Level')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="educationLevel" id="educationLevel" placeholder="<?php echo $tr->translate('Education Level');?>" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Specialty or skill')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="skill" id="skill" placeholder="<?php echo $tr->translate('Specialty or skill');?>" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Language')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="language" id="language" placeholder="<?php echo $tr->translate('Language');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Last Level')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="lastLevel" id="lastLevel" placeholder="<?php echo $tr->translate('Last Level');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Salary Updated')?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="salaryUpdated" id="salaryUpdated" placeholder="<?php echo $tr->translate('Salary Updated');?>" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Last Raise Salary')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"  name="lastRaiseSalary" id="lastRaiseSalary" placeholder="<?php echo $tr->translate('Last Raise Salary');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Old Work Place')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"  name="oldWorkPlace" id="oldWorkPlace" placeholder="<?php echo $tr->translate('Old Work Place');?>" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Expect Retire')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"  name="expectRetire" id="expectRetire" placeholder="<?php echo $tr->translate('Expect Retire');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Work Place Address')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"  name="workPlaceAddress" id="workPlaceAddress" placeholder="<?php echo $tr->translate('Work Place Address');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Current Address')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="currentAddress" id="currentAddress" placeholder="<?php echo $tr->translate('Current Address');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Expired Date')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="expiredDate" id="expiredDate" placeholder="<?php echo $tr->translate('Expired Date');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label style=" background: #068244;    padding: 5px;   color: #fff;" class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate('The name of the contact, Phone , Email Address In case of an emergency')?> :
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Contact Name');?> :</label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"  name="contactName" id="contactName" placeholder="<?php echo $tr->translate('Contact Name');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Phone Number');?> :</label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="phoneNumber" id="phoneNumber" placeholder="<?php echo $tr->translate('Phone Number');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Email Address');?> :</label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name=""emailAddress"" id="emailAddress" placeholder="<?php echo $tr->translate('Email Address');?>" />
	                   </div>
	                </div>
	                
	                <?php $sewe=0; if ($sewe==1){?>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Position Equal')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"  name="positionEqual" id="positionEqual" placeholder="<?php echo $tr->translate('Position Equal');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Certification Level')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="certification" id="certification" placeholder="<?php echo $tr->translate('Certification Level');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Certificate Code')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="certificateCode" id="certificateCode" placeholder="<?php echo $tr->translate('Certificate Code');?>" />
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Salary')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="salary" id="salary" placeholder="<?php echo $tr->translate('salary');?>" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-5" for="first-name"><?php echo $tr->translate('Seniority')?> :
	                   </label>
	                  <div class="col-md-7 col-sm-7 col-xs-7">
	                     <input type="text" class="form-control"   name="seniority" id="seniority" placeholder="<?php echo $tr->translate('Seniority');?>" />
	                   </div>
	                </div>
	               <?php }?>
			</div>
			<div class="col-sm-4">
				<div class="form-group">
					<div class="col-md-12 col-sm-12 col-xs-12 text-center">
                    	<div class="thumb-xl member-thumb m-b-10 center-block">
                            <img id="profile-img-tag" src="<?php echo $this->baseUrl()."/images/profile.jpg";?>" class=" img-thumbnail" alt="profile-image" style="height: 100%;width: 100%;">
	                        </div>
                        </div>
                 </div>
                 <div class="form-group">
                       <div class="col-md-12 col-sm-12 col-xs-12 m-t-10 text-center browe_photo">
                        <input type="file" id="profile-img" class="filestyle" data-input="false" name="photo" data-buttontext="<?php echo $tr->translate('BROWSE_PHOTO')?>">
                  	  </div>
                   </div>
                   <div class="form-group">
	                    <div class="col-md-12 col-sm-12 col-xs-12">
	                    	 <div class="text-center">
								<input id="btnsubmit" class="btn btn-primary black save" type="submit" value="<?php echo $tr->translate('SAVE');?>" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" /> 
			                </div>
	                    </div>
                    </div>
                   
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $('#profile-img-tag').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#profile-img").change(function(){
        readURL(this);
    });

    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57)) {
            var msg='You can input only number.';
    		alert(msg);
    		return false;
        }
        return true;
    }

    var url_checkEmployee = '<?php echo $this->url(array('module'=>'employee','controller'=>'index','action'=>'checkemplyeecode')); ?>';
    function CheckEmployeeCode(){
    	employeeCode = $('#employeeCode').val();
    	 var message = document.getElementById('error');
    	$.ajax({
            url: url_checkEmployee,
            type: "post",
            data: {'employeeCode':employeeCode},
            success: function(data){
                val = $.parseJSON(data);
    				if(val==1){
    					document.getElementById('btnsubmit').disabled=true;
    					 message.innerHTML = "<?php echo $tr->translate("Employee ID has already in other employee");?>";
    				}
    				else{
    					document.getElementById('btnsubmit').disabled=false;
    					message.innerHTML = "";
    				}

    			},
    			error: function(err) {
    				alert(err);
    			}
    		});
    }
</script>