<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("EMPLOYEE")); 
	echo $this->headTitle();
	$db = new Employee_Model_DbTable_DbEmployee();
	$position = $db->getSettingByValue("position");
	$ministry = $db->getSettingByValue("ministry");
	$person = $db->getSettingByValue("person");
	
	$urledit = $this->baseUrl()."/employee/index/edit";
	
	$number = array("០","១","២","៣","៤","៥","៦","៧","៨","៩");
	$month = array("01"=>"មករា", "02"=>"កុម្ភៈ", "03"=>"មិនា", "04"=>"មេសា", "05"=>"ឧសភា", "06"=>"មិថុនា", "07"=>"កក្កដា","08"=>"សីហា", "09"=>"កញ្ញា", "10"=>"តុលា","11"=>"វិច្ឆិកា", "12"=>"ធ្នូ");
	
	$url="http://".$_SERVER['HTTP_HOST'];
	$phblicpart = PUBLIC_PATH;
	$errorCorrectionLevel = 'L';
	$matrixPointSize = 4;
	//html PNG location prefix
	$PNG_WEB_DIR = $this->baseUrl().'/images/all/qrcode/';
	$PNG_TEMP_DIR = $phblicpart.DIRECTORY_SEPARATOR."images".DIRECTORY_SEPARATOR."all".DIRECTORY_SEPARATOR."qrcode".DIRECTORY_SEPARATOR;
	include $phblicpart.DIRECTORY_SEPARATOR."templates".DIRECTORY_SEPARATOR."phpqrcode".DIRECTORY_SEPARATOR."qrlib.php";
	
	$count = count($this->allemployee);
	$timeload="3000";
	if ($count>100){
		$timeload="9000";
	}
	if ($count<=10){
		$timeload="2000";
	}
?>   
<style>
img.status_icon {
    width: 16px;
}
div.search {
    padding: 0 2px;
    margin: 0;
}
span.select2.select2-container.select2-container--default {
    width: 100% !important;
}
</style> 
 <!-- START PAGE CONTENT -->
 <div id="page-right-content">
 	<div class="container">
    	<div class="row">
    		<div class="col-sm-12 border-botom">
    			<div class="col-sm-8">
    				<h4 class="m-t-0"><i class="ti-id-badge"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate("EMPLOYEE")?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    				<div class="buttun-block">
						<a class="btn btn-primary block" href="<?php echo $this->baseUrl()."/employee/index/add";?>"><?php echo $tr->translate("Add Employee")?></a>
						<a class="btn btn-primary black save" onclick="PrintDiv();" ><?php echo $tr->translate('Print Card');?></a>	
					</div>
    			</div>
    		</div>
			<div class="col-sm-12">
				<div class="card-box">
					<form name="frmlist_users" action=""  method="post">
						<div class="form-group">
                            <div class="col-md-4">
                                <input type="text" class="form-control" name="adv_search" id="adv_search"  placeholder="<?php echo $tr->translate("Search by employee id");?>" value='<?php echo $this->search['adv_search'];?>'>
								 </div>
                            <div class="col-md-1">
                            </div>
                             <div class="col-md-8 text-right">
                            	 <div class="form-group">
					                   <div class="col-md-2 text-left search">
					                 	  <select class="form-control select2" id="gender"  name="gender"  > 
					                 	  	<option value=""><?php echo $tr->translate('Gender')?></option>
					                   			<option value="male" <?php if ($this->search['gender']=="male"){ echo 'selected="selected"';}?>><?php echo $tr->translate('MALE')?></option>
					                   			<option value="female" <?php if ($this->search['gender']=="female"){ echo 'selected="selected"';}?>><?php echo $tr->translate('FEMALE')?></option>
											</select> 
					                   </div>
                                   	<div class="col-md-6 search">
                                     	<div class="input-daterange input-group" id="date-range">
                                          	<input type="text" class="form-control" name="start" value="<?php if (!empty($this->search['start'])){ echo date("m/d/Y",strtotime($this->search['start']));}?>" />
                                            <span class="input-group-addon b-0"><?php echo $tr->translate("to");?></span>
                                            <input type="text" class="form-control" name="end" value="<?php if (!empty($this->search['end'])){ echo date("m/d/Y",strtotime($this->search['end']));}?>" />
                                       </div>
                                   	</div>
                                   	<div class="col-md-3 text-left search">
					                 	  <select class="form-control select2" id="status"  name="status"  > 
					                 	  		<option value="-1"><?php echo $tr->translate('STATUS')?></option>
					                   			<option value="1" <?php if ($this->search['status']==1){ echo 'selected="selected"';}?>><?php echo $tr->translate('ACTIVE')?></option>
					                   			<option value="0" <?php if ($this->search['status']==0){ echo 'selected="selected"';}?>><?php echo $tr->translate('DEACTIVE')?></option>
											</select> 
					                   </div>
                                   <div class="col-md-1 search">
                                   	<button class="btn btn-primary " showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                                   	 </div>
                                 </div>
                            </div>
                       </div>
					</form>
					<div class="clearfix"></div>
				</div>
				<table id="datatable-buttons" class="table table-striped table-bordered">
					<thead>
    					<tr>
    						<th><?php echo $tr->translate("NUM");?></th>
    						<th><?php echo $tr->translate("Employee ID");?></th>
    						<th><?php echo $tr->translate("First Name Last Name");?></th>
    						<th><?php echo $tr->translate("Gender");?></th>
    						<th><?php echo $tr->translate("Framework");?></th>
    						<th><?php echo $tr->translate("POSITION");?></th>
    						<th><?php echo $tr->translate("Phone Number");?></th>
    						<th><?php echo $tr->translate("STATUS");?></th>
    					</tr>
    				</thead>
    				<tbody>
    					<?php 
    					if (!empty($this->allemployee)) 
    						foreach ($this->allemployee as $key => $employee){
    							$images = $this->baseUrl()."/images/icon/active.png";
    							if ($employee['status']!=1){
    								$images = $this->baseUrl()."/images/icon/blocked.png";
    							}
    						?>
    					<tr>
    						<td><?php echo $key+1;?></td>
    						<td><a class="edit" href="<?php echo $urledit."/id/".$employee['id'];?>"><?php echo $employee['employeeCode'];?></a></td>
    						<td><a class="edit" href="<?php echo $urledit."/id/".$employee['id'];?>"><?php echo $employee['firstName']." ".$employee['sureName'];?></a></td>
    						<td><?php echo $tr->translate(strtoupper($employee['gender']));?></td>
    						<td><?php echo $employee['framework'];?></td>
    						<td><?php echo $employee['positionTitle'];?></td>
    						<td><?php echo $employee['phoneNumber'];?></td>
    						<td class="text-center"><img class="status_icon" src="<?php echo $images;?>" /></td>
    					</tr>
    					<?php }?>
    				</tbody>
				</table>
				<div id="divPrint" class="form-group" style="display: none;">
					<style>
								ul.list-data {
								    list-style-type: none;
									font-size: 12px;
									padding: 0;
								}

								ul.list-data span.title {
								    min-width: 3cm;
								    display: inline-block;
									font-family: Arial,'Khmer OS Muol Light';
								}
								ul.list-data span.title_value.up{
									text-transform: uppercase;	
									font-weight: 600;
								}
								span.title_gender {
								    padding-left: 55px;
									font-family: Arial,'Khmer OS Muol Light';
								}
								.foot-right-block,.foot-left-block,
								.left-block, .right-block,
								.last_footer .left,
								.last_footer .right {
								    display: inline-block;
								}
								.right-block {
								    width: 74%;
									 vertical-align: top;
								}
								.left-block {
								    width: 25%;
								 vertical-align: top;
    								text-align: center;
								}
								.left-block .photo {
								    
								    text-align: center;
								  
								}
								.left-block .photo img{
									width: 85px;
								  height: 105px;
								}
								.foot-left-block {
								        width: 54%;
								    vertical-align: top;
								}
								.last_footer .left{
									width: 54%;
								}
								.last_footer .left,
								.foot-left-block p {
								    font-size: 10px;
								}
								.last_footer .right,
								.foot-right-block {
								    width: 45%;
								    text-align: center;
								    vertical-align: top;
								}
								.last_footer .right,
								.foot-right-block p {
								    font-size: 11px;
								}
								.qrimages {
								    width: 47%;
								    text-align: center;
								}
								.qrimages img {
								    width: 80px;
								}
							  
							    div.pagese{ page-break-inside:always; page-break-after:always; }
                    		</style>
				<?php if (!empty($this->allemployee)){
					
					foreach ($this->allemployee as $key => $employee){
						$profile = $this->baseUrl()."/images/profile.jpg";
						if (!empty($employee['profilePhoto'])){
							$profile = $this->baseUrl()."/images/all/".$employee['profilePhoto'];
						}
							
							
						$filename="";
						if (!empty($employee['employeeCode'])){
							$filename = $PNG_TEMP_DIR.md5($employee['employeeCode'].'|'.$errorCorrectionLevel.'|'.$matrixPointSize).'.png';
							if (file_exists($filename)){
								
							}else{
								QRcode::png($url.$this->baseUrl()."/index/employee?information=".$employee['employeeCode'], $filename, $errorCorrectionLevel, $matrixPointSize, 2);
							}
						}	
					?>
						<div class="pagese">
							<div  class="card-employee" style=" line-height: 18px;   border: solid 1px #cecccc;    border-radius: 5px;    width: 14cm;    padding: 10px;  color: #0864ad; font-family: Arial, sans-serif,'Kh Battambang','Khmer Battambang';">
                    		<div class="left-block">
                    			<div class="photo">
                    				<img  src="<?php echo $profile;?>" alt="profile-image" >
                    			</div>
                    		</div>
                    		<div class="right-block">
                    			<?php 
                    				$dob = strtotime($employee['dob']);
                    				$spp = str_split(date("d",$dob));
									$day="";
									foreach ($spp as $ss){
										$day.=$number[$ss];
									}
									$mm = str_split(date("m",$dob));
									$dmonth="";
									foreach ($mm as $ss){
										$dmonth.=$number[$ss];
									}
									$yy = str_split(date("Y",$dob));
									$year="";
									foreach ($yy as $ss){
										$year.=$number[$ss];
									}
									?>
                    			<ul class="list-data">
                    				<li><span class="title">អត្តលេខ</span><span class="title_value">: &nbsp;&nbsp;<?php echo $employee['employeeCode'];?></span></li>
                    				<li><span class="title">គោត្តនាម-នាម</span><span class="title_value">: &nbsp;&nbsp;<?php echo $employee['firstName']." ".$employee['sureName'];?></span><span class="title_gender">ភេទ</span><span class="title_value"> &nbsp;&nbsp;<?php if ($employee['gender']=='male'){echo "ប្រុស";}else{echo "ស្រី";};?></span></li>
                    				<li><span class="title">(ជាអក្សរឡាតាំង)</span><span class="title_value up">: &nbsp;&nbsp;<?php echo $employee['latinName'];?></span></li>
                    				<li><span class="title">ថ្ងៃ ខែ ឆ្នាំកំណើត</span><span class="title_value">: &nbsp;&nbsp;<?php echo $day."-".$dmonth."-".$year;?></span></li>
                    				<li><span class="title">អង្គភាព</span><span class="title_value">: &nbsp;&nbsp;<?php echo $employee['organization'];?></span></li>
                    				<li><span class="title">ឋានៈ</span><span class="title_value">: &nbsp;&nbsp;<?php echo $employee['positionTitle'];?></span></li>
                    			</ul>
                    		</div>
                    		<div class="foot-left-block">
                    			<div class="qrimages">
                    				<img  src="<?php echo $PNG_WEB_DIR.basename($filename);?>" alt="profile-image" >
                    			</div>
                    		</div>
                    		<div class="foot-right-block">
                    			<?php 
                    				$dateNow = str_split(date("d"));
									$Nday="";
									foreach ($dateNow as $ss){
										$Nday.=$number[$ss];
									}
									
									$yNow = str_split(date("Y"));
									$Nyear="";
									foreach ($yNow as $ss){
										$Nyear.=$number[$ss];
									}
									
									?>
                    			<p>រាជធានីភ្នំពេញ. ថ្ងៃ ទី <?php echo $Nday;?> ខែ<?php echo $month[date("m")];?> ឆ្នាំ<?php echo $Nyear;?><br />
                    			<?php if(!empty($position['value'])){ echo $position['value'];}?><br />
                    			<?php if(!empty($ministry['value'])){ echo $ministry['value'];}?>
                    			</p>
                    			<br />
                    			
                    		</div>
                    		<div class="last_footer">
                    			<div class="left">
                    				<p>ករណីបាត់ ឬខូចត្រូវរាយការណ៍ជូននាយកដ្ឋានបុគ្គលិក។<br />
                    				អ្នកក្លែងបន្លំប័ណ្ណសម្គាល់ខ្លួនមន្ត្រីរាជការនឹងត្រូវផ្ដន្ទាទោសតាមច្បាប់។</p>
                    			</div>
                    			<div class="right">
                    			<p><?php if(!empty($person['value'])){ echo $person['value'];}?></p>
                    			<br />
                    			</div>
                    		</div>
                    	</div>
						</div>
						
					<?php 
					}
				}?>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END PAGE CONTENT -->

<script>
var timeout ='<?php echo $timeload;?>';
function PrintDiv() {
	loading();
    var contents = document.getElementById("divPrint").innerHTML;
    var frame1 = document.createElement('iframe');
    frame1.name = "frame1";
    frame1.style.position = "absolute";
    frame1.style.top = "-1000000px";
    document.body.appendChild(frame1);
    var frameDoc = (frame1.contentWindow) ? frame1.contentWindow : (frame1.contentDocument.document) ? frame1.contentDocument.document : frame1.contentDocument; frameDoc.document.open();
    frameDoc.document.write('<html><head><title>Employee ID</title>');
    frameDoc.document.write('</head><body>');
    frameDoc.document.write(contents);
    frameDoc.document.write('</body></html>');
    frameDoc.document.close();
    setTimeout(function () {
        window.frames["frame1"].focus();
        window.frames["frame1"].print();
        document.body.removeChild(frame1);
        closeloading();
    }, timeout);
   return false;
}
</script>